### ISSUE TITLE
Error "Unknown option 'disable-web-security'" when opening .md files with mindforger MSWindows.

### ISSUE THREAD

**Issue by dylb0t** [dvorka/mindforger#1006]
Fresh install, .md filetype is not associated with any program, so you must choose which. 
If you choose to open with mindforger.exe located in bin directory, an error is presented "Unknown option 'disable-web-security'". If you drag a .md file onto mindforger.exe, same error is given. If you use File > Open > Markdown file, no error is given and .md file is opened successfully.

Thank you
Dylan
MindForger 1.49.0

**Comment by dylb0t** [comment]
![image](https://user-images.githubusercontent.com/36675473/55363350-a8c53b80-5491-11e9-9186-f9010233d111.png)

**Comment by dylb0t** [comment]
Running from Command Line 
`
user@hostname:/mnt/c/Program Files/MindForger/bin> ./mindforger.exe --help
Unknown option 'disable-web-security'.
`
I am using WSL, but did not use WSL to install as I use SUSE and not Ubuntu. 
It appears as though an option is missing in the Windows binary compilation. I found references to this option in a bug report about OSX problems. You had to run with this option or it wouldn't open. Here: #1005 

I am excited to get working with this, if I don't hear anything I may need to stand up an Ubuntu WSL instance and install from there.

**Comment by vlastahajek** [comment]
Nice catch @dylb0t , thanks. I can confirm this. 
Just two notes:
- I see you reported that on 1.49.0. Please, update that with 1.49.2 cause it contains an important fix.
- MindForger is also Windows native binary since 1.49.0, you don't need WSL.

**Comment by dylb0t** [comment]
Thank you I will download 1.49.2. Opened #1007 to fix the destination of the "Download Now" link in the post announcing 1.49.2.

**Comment by dylb0t** [comment]
Reported error persists in 1.49.2. GUI also does not draw and error is raised, separate issue. Raised in #1008.

**Comment by vlastahajek** [comment]
The reported issues is not fixed in 1.49.2. That version brings different stability fix above 1.49.0.

**Comment by dvorka** [comment]
Reconcile #1005 and #1006 - Qt documentation, more robust handling and user documentation.
