### ISSUE TITLE
1.49.2 Windows does not launch

### ISSUE THREAD

**Issue by dylb0t** [dvorka/mindforger#1008]
Launch icon does not work. No error message window raised.

Command line tests:
> user@hostname:/mnt/c/Program Files/MindForger/bin> ./mindforger.exe
(nothing happens for 5 seconds)

> user@hostname:/mnt/c/Program Files/MindForger/bin> ./mindforger.exe -v
> Unknown option 'disable-web-security'.

error raised in application log (event viewer)
> Faulting application name: mindforger.exe, version: 1.49.0.2, time stamp: 0x5c852650
> Faulting module name: ucrtbase.dll, version: 10.0.17134.619, time stamp: 0xf74cf274
> Exception code: 0xc0000409
> Fault offset: 0x000000000006ca78
> Faulting process id: 0x1be4
> Faulting application start time: 0x01d4ea4800097467
> Faulting application path: C:\Program Files\MindForger\bin\mindforger.exe
> Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
> Report Id: e6b1e364-ba0a-4b35-8156-af82dbb998d5
> Faulting package full name: 
> Faulting package-relative application ID: 

info raised (informing of WER creation)
> Fault bucket 1383224485457971558, type 5
> Event Name: BEX64
> Response: Not available
> Cab Id: 0
> 
> Problem signature:
> P1: mindforger.exe
> P2: 1.49.0.2
> P3: 5c852650
> P4: ucrtbase.dll
> P5: 10.0.17134.619
> P6: f74cf274
> P7: 000000000006ca78
> P8: c0000409
> P9: 0000000000000005
> P10: 

Not sure if you have interest in the wer file.

**Comment by dylb0t** [comment]
Hmm. More information.
Not sure this is solely a 1.49.2 issue. 
- I upgraded from 1.49.0, and this was the behaviour
- Uninstalled / reinstalled 1.49.0 and this behaviour continued.

This is even with restarts.

**Comment by vlastahajek** [comment]
To investigate not launching problem, please, try this:
1. Remove/rename **.mindforger.md** in your Windows user home (`c:\users\username\.mindforger.md`) 
2. Remove/rename default repository from your Documents folder (`c:\users\username\Documents\mindforger-repository`) 
3. Launch MindForger from Start menu

Does the issue still persist?

**Comment by dylb0t** [comment]
Renamed indicated document and folder, installed. Issue resolved. I guess this was a problem with instaler/uninstaller as suspected.

Thank you for the direction!

**Comment by vlastahajek** [comment]
The problem could have  other reasons. The test above just verified that clean installation works. 

Could you, please, try to put back old `.mindforger.md` and start MindForger over?

If you again observe that nothing happens, please, do following:
1. look at processes list to check whether mindforger.exe is there or not.
2. Copy here your `.mindforger.md` , if possible.

**Comment by dylb0t** [comment]
Replaced .mindforger.md, mindforger failed to launch. 
Watched task manager. Program opens and then closes after a couple of seconds. Does not remain open in a hung state.
Diff between mindforger.md files

kzin@hostname:/mnt/c/Users/user.name> diff .mindforger.md .mindforger.md.bak2
9c9
< * Mind state: sleep
---
> * Mind state: think
72d71
< * Repository: C:\Users\user.name\.mindforger.md
74d72
< * Repository: C:\Users\user.name\OneDrive - Corporate\Notebooks\Text Notes

Broken MD attached 

[mindforger.md.redacted.txt](https://github.com/dvorka/mindforger/files/3082469/mindforger.md.redacted.txt)

**Comment by dvorka** [comment]
Ideas:
* might be space in the windows path - configuration unit test to be added both for linux and window
