### ISSUE TITLE
Paste Images easily

### ISSUE THREAD

**Issue by qlixed** [dvorka/mindforger#1014]
Allow to paste images in a easy way.
I think that we can create a images directory on the repository (or directory in "Markdown Editor Mode") and then write a file there, adding a link to the image in the note at cursor position to show it.
I will try to do something like this and put a pull request.
Let me know if you think that we need or want to change the implementation. I will clone the repo and try to implement it.

**Comment by dvorka** [comment]
@qlixed That would be really **great**! Other users already asked for this feature (I even created #495 (which is basically duplicate) so your contribution would be highly appreciated :wink: 

Originally I planned to name images like `<NOTEBOOK NAME>-<IMAGE NAME>.<EXTENSION> for example:
* notebook is `mf/memory/my-notebook.md`
* name of the image being pasted `my-image.png`
* image created in MindForger repository: mf/memory/my-notebook.my-image.png`
... but it's just a proposal. Feel free to design it as it's suitable for your. I have only one suggestion - images should be stored somewhere under `memory/` directory.

Thank you for your interest in MindForger!

**Comment by dvorka** [comment]
Feature released in https://github.com/dvorka/mindforger/releases/tag/1.50.0 and verified in 3d2cec6f6cf0b80c353a667973e68d972f3936ce
