### ISSUE TITLE
Improve usability: Warn that child Ns will be deleted (dialog)

### ISSUE THREAD

**Issue by jghyllebert** [dvorka/mindforger#1015]
I just started using mindforger and accidently deleted half of my notes in my Notebook.

# Steps to reproduce

1. Create a new notebook
![Screenshot from 2019-04-10 01-56-23](https://user-images.githubusercontent.com/1712550/55855200-da46a280-5b34-11e9-92be-1837061abd04.png)

2. Start writing in provided note
![Screenshot from 2019-04-10 02-00-04](https://user-images.githubusercontent.com/1712550/55855261-06faba00-5b35-11e9-9051-babbfb4a4815.png)

3. Close and restart Mindforger, open notebook. Notice original note has been split up in multiple notes. (Wasn't expecting that)
![Screenshot from 2019-04-10 02-00-20](https://user-images.githubusercontent.com/1712550/55855333-39a4b280-5b35-11e9-8cc7-2b90163be3d2.png)

4. Create a new note, while having note 'Note 1' selected, have it positioned 'Below Selected Note'.  (By clicking on the + button top left, sorry forgot to take screenshot)
5. Realising created note is not a sub-note of 'Title 1'
![Screenshot from 2019-04-10 02-01-03](https://user-images.githubusercontent.com/1712550/55855518-bfc0f900-5b35-11e9-94eb-b1e0c41da311.png)
6. Press Delete button on keyboard
7. 'Subtitle 1.3' not has been deleted, as well as the other subtitles
![Screenshot from 2019-04-10 02-01-25](https://user-images.githubusercontent.com/1712550/55855590-f4cd4b80-5b35-11e9-8a74-4681e4a49144.png)

# Expected behaviour
I wish it wouldn't delete the other notes, there was no indication whatsoever this would happen.

**Comment by dvorka** [comment]
Jonas, I'm very sorry that you lost your data. I will try to improve the usability as follows:

1. MindForger will warn you that multiple notes will be deleted (dialog).
2. I will try to implement and `undo` even for these modifications.

I'm curious about the behavior you expected - you deleted **parent** note of `Subtitle 1.x` notes - how should be layout changes? Which note should be parent of `Subtitle 1.x`?

Thank you for you feedback and interest in MindForger!

**Comment by jghyllebert** [comment]
> I'm curious about the behavior you expected - you deleted parent note of Subtitle 1.x notes - how should be layout changes? Which note should be parent of Subtitle 1.x?

In my perception **below** means lower than something else, thus thinking I'd be creating a sub note of `Title 1`.
But, in reality the new note got put **after** `Title 1` on the same hierarchical level.

What I far from expected was that the new note would be the owner of the sub notes that were originally owned by `Title 1` in my case.

**Comment by dvorka** [comment]
Makes sense. 

MindFoder uses parent-child relationship for up/down move, promotion/demotion, refactoring and also deleting. I think that the best solution will be to ask user whether the note **with** or **without** child notes should be deleted.

Thanks!

**Comment by pezy** [comment]
When I delete the **parent** note, I hope the children can **up** to the parent level by default.
In any case, **undo** must work...  😭

**Comment by dvorka** [comment]
Q dialog will be released w/ 1.50.x
