### ISSUE TITLE
Kanban board view

### ISSUE THREAD

**Issue by Pich78** [dvorka/mindforger#1018]
One think it can be useful is another view in addition to Eisenhower Matrix: a Kanban view.

It can be created and customized a set of tags for the kanban view ( for example: BackLog, Today, Working, Waiting, Done ), then when the kanban view is selected, a group of column can show each task under the proper column.
Additional idea: when passing the mouse over a task, a tool tip will show a small text excerpt.

**Comment by dvorka** [comment]
@Pich78 This is very nice idea! I like it! Let me add it to the plan...

**Comment by michaelsjackson** [comment]
Could be useful in lecture situations as well.

**Comment by dvorka** [comment]
... increasing priority ;)

**Comment by Iznik285** [comment]
I also like this idea. Sounds good.

**Comment by dvorka** [comment]
![kanban](https://user-images.githubusercontent.com/2090143/139556529-6fc6b78a-4210-4740-9bf4-e4596abe9900.png)

@Pich78 @Iznik285 @michaelsjackson FYI kanban ready for 1.53.0 release.

**Comment by Pich78** [comment]
Thank you! as soon as the release is done, I will test it!

**Comment by dvorka** [comment]
https://user-images.githubusercontent.com/2090143/140654760-ae893a5a-bdca-4dcf-a799-060675f0ef20.mp4

Short demo of Kanban on tags.

**Comment by Pich78** [comment]
Very nice!
2 questions:
1) I see that you can bind the column to a tag: this is perfect! Is the column number limited to 4?
2) Do you have any mechanism in mind to move a line from a column to another? For example right-click -> move to (choose from one of the columns already present) or drag and drop?

**Comment by dvorka** [comment]
@Pich78 please find my answers below:

1. There can be 1 to 4 columns. This was the highest number which horizontally scaled without scrolling. Do you think that it is not enough? Should there by any number of columns / higher number of columns? 
2. Currently there are keyboard shortcuts <kbd>Ctrl-right</kbd> and <kbd>Ctrl-left</kbd> which can be used to move current Notebook or Note between columns. Moving to next / last column can be done using <kbd>tab</kbd> and <kbd>Shift-tab</kbd>. You will be also able to use menu (`Organizer/Move to next` ...). I wanted to implement drag & drop, however, I didn't find technical solution (for now).

Thank you for your interest in MindForger and this feature!

**Comment by Pich78** [comment]
Regarding the number of columns, maybe adding more columns will move the app to a domain that is not his target.
Basic task processing kanban boards have 3 columns (Todo, in Process, done).
A general kanban software (e.g. Trello) can have unlimited columns. More advanced kanban apps can also have swimlanes, but Mindforger in its nature it’s not a kanban app.
The main concern with most commercial kanban app is that you put your data inside and they are “trapped” inside someone’s servers.
I’m thinking from a long time to a kanban app where you can own your data and Mindforger has a good data model.
I think this feature can be left as is now because it’s good (I’m waiting to test it!) and tested to see if any additional request/development is required.

**Comment by dvorka** [comment]
Thank you for the review and sharing your opinion :pray: I agree. Which operating system (and distro) do you use?

**Comment by Pich78** [comment]
I use Mac OS/ Windows
