### ISSUE TITLE
Warn or indicate editing a read-only file

### ISSUE THREAD

**Issue by kcthrn** [dvorka/mindforger#1039]
Didn't know a file I was editing was read-only.

The "Notebook saved!" message on the status bar was misleading :frowning_face:. I lost some data because of this. Don't worry about it though, I still love the program. If I knew C++ I would definitely contribute.

**Comment by dvorka** [comment]
@kcthrn Oh, I'm very sorry that it happened - I completely missed this use case. Obviously it's bug - I'm adding it as high priority feature to the next release. Thank you for your interest in MindForger and feedback! :+1:

**Comment by dvorka** [comment]
Proposed solution:

* [ ] O to have RD_ONLY flag (might be useful also in the future)
* [ ] Flag will be checked on editor openning - in case of RD_ONLY it will show info dialog and doesn't open editor view, but will keep view mode.
