### ISSUE TITLE
Install Handshake failed

### ISSUE THREAD

**Issue by P4ulJC** [dvorka/mindforger#1043]
Can not install mindforger on Debian or Ubuntu due to the following:

Err https://www.mindforger.com stretch/main amd64 Packages                     
  gnutls_handshake() failed: Handshake failed
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Err https://www.mindforger.com stretch/main i386 Packages                      
  gnutls_handshake() failed: Handshake failed

**Comment by dvorka** [comment]
Trusty (and older Ubuntu versions) along with Debian equivalents are unfortunately not supported due to compilation problems (old compiler and Qt versions).
