### ISSUE TITLE
Edit notes not possible on external display

### ISSUE THREAD

**Issue by avdn2011** [dvorka/mindforger#1047]
When installing MindForger (1.49.2) on a Windows 10 laptop it is working fine as long as it is shown on the laptop screen. 

After moving the MindForger window to an external display (extended desktop) the notebooks and notes can not be viewed or edited. Also several toolbar icons are not functioning.

**Comment by vlastahajek** [comment]
Weird, no problem on my laptop (1920x1080) with external monitor (1920x1200) as extended screen. Windows 10 Prof.

**Comment by avdn2011** [comment]
Strange indeed. I tried another external display on another location and... no problems. Perhaps it has to do something with drivers or the fact it is a dual external screen setup.
