### ISSUE TITLE
How to Add Images?

### ISSUE THREAD

**Issue by mokane99** [dvorka/mindforger#1048]
Can't figure out how to add images. 
Or even find the html view.
View options are greyed out.
![Screen Shot 2019-09-03 at 20 11 56](https://user-images.githubusercontent.com/20384813/64223034-2a792500-ce87-11e9-99ed-fe2888bd7a69.png)
Can't find user manual.

**Comment by dvorka** [comment]
Adding of images using drag & drop including copying them to MF repository implemented by 0a7f39663993205e8726e44633fcb07cb7631896 - will be released w/ MindForger 1.50
