### ISSUE TITLE
MaxOS Home/End Support

### ISSUE THREAD

**Issue by stexyz** [dvorka/mindforger#1052]
`home` and `end` commands in note editor don't work 

**expected** `command` + `left/right arrow` = home/end and/or `fn` + `arrow` = home/end (on the line)); 

**current behaviour**: in MF it promotes/demotes the section even without focus on the left pane

**Comment by dvorka** [comment]
Workaround to enable normal keyboard use: disable <kbd>Ctrl-</kbd>up/.../right accelerators on MacOS

**Comment by dvorka** [comment]
Keys disabled - closing. In case you have a suggestion for new key accelerators please reopen.
