### ISSUE TITLE
Allow spaces in markdown links

### ISSUE THREAD

**Issue by stexyz** [dvorka/mindforger#1054]
Images in markdown do not recognise path with spaces as image (important due to Onedrive and others); possibly problem with all links `[show-text](/path with spaces)`

**Comment by dvorka** [comment]
Other valid example w/ title: `[I'm an inline-style link with title](https://www.google.com "Google's Homepage")
`

**Comment by dvorka** [comment]
Implemented by 1c56e5c694ca74a04d1dd49a8b026380ea30c512
