### ISSUE TITLE
Space before heading

### ISSUE THREAD

**Issue by mseliger** [dvorka/mindforger#1056]
When entering a heading as a first line of a note then the programs adds himself a space before the heading.
Original
     '## Test'
After saving
    ' ## Test'

**Comment by stexyz** [comment]
If I'm not mistaken this is intended (escaping the `##`) .

The idea is to insert notes (=lvl 2 (`##`) blocks into the outline/document through menu (Note->New).

**Comment by dvorka** [comment]
Duplicate of #665
