### ISSUE TITLE
Problem with '---'

### ISSUE THREAD

**Issue by GraphDelivery** [dvorka/mindforger#1060]
when a '---' is placed without blank row below some Text, the Text appears bold and the line is drawn dense and later on after reopening the Mindforger it appears as a separate note in it's notebook !
This is appearently not wanted.

**Comment by dvorka** [comment]
@GraphDelivery thank for 🐞 report - fixed 7e22205 will be releases in `1.54.0`

**Comment by Iznik285** [comment]
Tested on Windows 10 20H2 and 1.53.540 ee5bd2fd. All is working as expected
