### ISSUE TITLE
Full O preview

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#1081]
Checkbox w/ header **or** full preview on N opening:

* [x] full preview rendering
* [x] Preferences/View/Whole notebook HTML preview (1st section only otherwise)
* [x] Outline header view **button**: <kbd>Toggle Full Preview</kbd>
* [x] When toggle hoisting on O header directly show full or header preview only.

**Comment by en3r0** [comment]
Does this mean I would be able to view the entire file all at once without being forced to view each "Note" separately?

**Comment by dvorka** [comment]
@en3r0 Yes, exactly.

**Comment by dvorka** [comment]
Implemented in e47c8d6be676f1f3da9c588c561279824b1d7676
