### ISSUE TITLE
[Window] Application freezes and not respond (privileges)

### ISSUE THREAD

**Issue by Nedptr** [dvorka/mindforger#1150]
Hey I just installed gameforger with windows installer, I started the application and opened a file(for example installation).
the application freezes and not respond few seconds just after opening the file.

i'm on windows 10

**Comment by Nedptr** [comment]
running the application as admin seems to fix the issue. any ideas why is that

**Comment by dvorka** [comment]
@Nedptr thanks for the report - let me check privileges & older bugs. I'm also close to the release which has several Win specific fixes. Perhaps trying a nightly build would help.
