### ISSUE TITLE
Crossout or Fade Disabled Menu Item

### ISSUE THREAD

**Issue by s0kil** [dvorka/mindforger#1161]
When a menu item is disabled, it would be good to fade it or cross it out.

![Screenshot from 2020-01-19 02-36-37](https://user-images.githubusercontent.com/24403355/72676932-a1910d80-3a64-11ea-9b31-06da6946d9c8.png)

**Comment by dvorka** [comment]
![disabled](https://user-images.githubusercontent.com/2090143/73123278-8a837b80-3f8e-11ea-9406-0f75a51cfccb.png)
+ menu items got the same style as well.

**Comment by dvorka** [comment]
Will be released w/ 1.51
