### ISSUE TITLE
Cannot extract text from note

### ISSUE THREAD

**Issue by Luladjiev** [dvorka/mindforger#1170]
Hello, first of all, thanks for making this tool.
Looking at your youtube videos you can edit a note and extract text from it.
However when I try this, the Note menu becomes disabled once I start editing a Note.
Is there a way to extract text from notes?

**Comment by dvorka** [comment]
@Luladjiev unfortunately it's bug (I changed enable/disable menu logic) - will need to move `Extract` action to `Edit` menu group.

**Comment by dvorka** [comment]
@Luladjiev Fix will be released w/ MindForger 1.51 Thanks again Peter!
