### ISSUE TITLE
1.50 for the Mac?

### ISSUE THREAD

**Issue by technovangelist** [dvorka/mindforger#1199]
Will 1.50 be released for the Mac? I see the latest for the Mac is still 1.49

**Comment by dvorka** [comment]
I just need to get access to a macOS machine. It should take ~2 weeks.

**Comment by StefanoCecere** [comment]
can we help somehow with the macOS builds?

**Comment by dvorka** [comment]
@StefanoCecere Thank you for asking Stefano! I really appreciate that you care! There is no problem from code perspective, I just don't have access to a macOS machine where I could build MindForger distro. 

What would help me would be macOS maintainer. Also if you/anybody knows (have real experience with) a good cloud service where I could rent macOS virtual machine w/ plan which would allow me to do the build please let me know. If everything goes well I should get access to macOS machine in ~2 weeks.

Also there is description of how to build MindForger on macOS https://github.com/dvorka/mindforger-repository/blob/master/memory/mindforger/installation.md#build-on-macos-  ... yes, it's a bit complicated.

**Comment by technovangelist** [comment]
I saw how much cooler 1.50 was on a linux vm so went through the build process on the mac. It seems to work well. I am not totally sold on using the tool yet, but if you need a build, I may be able to provide.

**Comment by technovangelist** [comment]
and now built 1.51.

**Comment by technovangelist** [comment]
I haven't used CircleCI but have known many who have. They have a MacOS build environment and will build open source projects for free. https://circleci.com/open-source/

**Comment by dvorka** [comment]
@technovangelist Thank you Matt for CI suggestion! As I mentioned above, I should get access to physical macOS machine in ~2 weeks and build distro there. If it fails, I rent a VM OR would ask you for help OR will buy a HW. Thanks! :+1:

**Comment by StefanoCecere** [comment]
but if CircleCI is free for opensource.. why don't we try to make macOS builds straight from there?

**Comment by dvorka** [comment]
@technovangelist @StefanoCecere @stefxy I just built MindForger 1.52.0 **release candidate** nightly build:

* http://www.mindforger.com/TRANSFER/mindforger-1.52.NIGHTLY-20200306.dmg

I have borrowed MacBook until Sunday - if you find any problem, have any macOS specific requirement (like key bindings, macOS native features, ...) please let me know.

**Comment by ajgon** [comment]
@dvorka Checked the Nightly, and code fonts work as expected 👍 Thank you!

**Comment by dvorka** [comment]
My pleasure :wink:

**Comment by dvorka** [comment]
https://github.com/dvorka/mindforger/releases/tag/1.52.0 w/ macOS distro released :tada:
