### ISSUE TITLE
View: Os outline ~ hierarchical notebooks

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#1200]
Introduce new view which will allow Os organization into tree.

Hints:

* Separate view (not combined w/ tree list).
* O has parent O (stored in metadata).
* O has offset position in O view.
* Deleting O simply removes it from the view w/o fixing parent/child tree structure (O will be deeper).
* Adding O will add it as child of current O (when editing O/N, when on Os table).

HonzaO

**Comment by Kochise** [comment]
Regarding https://github.com/dvorka/mindforger/issues/1358#issuecomment-883485779

It would be super cool to maintain a `GitHub` repository and separate topics in dedicated MD files, but I don't know how you plan to move things around in sub-folders to mimic the tree hierarchy.

**Comment by dvorka** [comment]
Implemented by 7a65251d589d7d6ff1e0da3ef6eb9dd6ad23ce78 in `enh-1200/o-tree`
