### ISSUE TITLE
Copying image to repository don't work on Windows (1.50.1)

### ISSUE THREAD

**Issue by and3md** [dvorka/mindforger#1207]
Hi, 
At first many thanks for your great work. MindForger is awesome! 

I found small issue on Windows. Copy image to repository don't work. I think it's file path delimiter or disk letters problem. On Linux works OK.

## Steps to reproduce:
1. Download Mind Forger [logo](https://www.mindforger.com/images/mind-forger.png) from www to downloads folder (mind-forger.png)
2. In Mind Forger, edit note, 
3. Click Format->Image menu item 
4. In window check copy to repository
5. Select downloaded file (mind-forger.png)
6. Click Insert

The path will be:
```
![Image](test.C:/Users/<user>/Downloads/mind-forger.png)
```
For test notebook.
Regards

**Comment by dvorka** [comment]
@and3md thank you for kind works Andrzej! I plan to work on MindForger Win bugs and enhancements tomorrow. Thank you for the report!

**Comment by dvorka** [comment]
Fixed c67146c will be released w/ MindForger 1.51.0

**Comment by and3md** [comment]
Now works great, thanks for fixing that so fast :)

**Comment by dvorka** [comment]
👍 BTW you can also drag and drop image or file when editing a note.
