### ISSUE TITLE
Outline font size

### ISSUE THREAD

**Issue by Honos2014** [dvorka/mindforger#1218]
Mindforger looks like a promising candidate for my all notes taking, but I cannot find how I can choose the outline font size and interface in general. The font is too small for me with my high-resolution screen.
Which css or config should I change?
Thank you

**Comment by dvorka** [comment]
If you want to change font size in the **editor**, then use menu `File/Preferences/Editor tab/Editor font`.

If you want to change font size in the (HTML) **viewer**, then either click to the preview and use <kbd>Ctrl</kbd> and mouse wheel/scroll to zoom in/out **or** use menu `File/Preferences/Viewer/HTML zoom` and put there number like 200 (for 200% zoom).

Thank you for your interest in MindForger!

**Comment by Honos2014** [comment]
![2020-02-21_17-55](https://user-images.githubusercontent.com/9630401/75078375-71111900-54d3-11ea-96d4-77ddac6f93b8.png)
Thank you for your help.
I attached an image showing the section with the small font. Editor and HTML are ok.
It's in the outline who is too, small.
Mindforger is deffinitively a great note taking program.

**Comment by Honos2014** [comment]
Hi,
I've been able to change the dpi of my display to get it readable.
Those font are from QT or GTK?
Thank you. Feel free to close this issue.

**Comment by dvorka** [comment]
@Honos2014 Thanks!

I use MindForger in HD and 2k (my machines), 4k (at work). I increased OS/window manager font size to make it readable and it worked for me nicely - analogous operation of what you did. Changing MindForger menu/tables/... sizes is otherwise complicated due to geometry.

Thank you for your interest in MindForger!

(closing)

**Comment by dmitryt** [comment]
it might be more convenient to manage this font size within the app instead of changing the font size globally.
