### ISSUE TITLE
[Autolinking] N or O header live preview to be w/o meta on switch to edit w/ live preview 

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#1233]
* [x] refresh preview on opening edit perspective for **header**
* [x] refresh preview on opening edit perspective for **note**

... by setting hits counter

**Comment by herop** [comment]
***Autolinking*** is a killer feature for me and your description is teasing that marvel.
But I can't find where to enable it (no, it's not in the menu) or any other way to do it. Please help me out here. Thank you,
Jochen

**Comment by dvorka** [comment]
@herop autolinking is killer feature also for me... therefore it has a bit complicated history. I released previews of autolinking in the past, but did complete rewrite since then. Autolinking is hidden in `1.51.0` (and perhaps also in a few older versions), because it was not stable enough.

**However**, I finished the rewrite of autolinking last week (the best one I ever had) and (if everything goes well) I would like to release it this weekend. :crossed_fingers: Please stay tuned.

**Comment by herop** [comment]
Ha, don't we live in interesting times. 😄 
I can't wait to take it for a spin.
It will as well be available in the _Windows_ version too, I hope?
If you could update your how-to section as well, would be formidable.
I tried ROAM and was compelled, how backlinking is implemented and now be very eager to learn how you interpret autolinking in your **thinking notebooks**.
While I'm at it: 
- I wasn't able to grasp your idea of notes and notebooks
- Am I mistaken or are notes just segments (Notion would call them blocks) of a notebook?
- One more thing: I struggle to get back to, say all notebooks if I open one of them
- For example, I open the MF User Documentation and then I can't see a way to get back to the repository without opening it explicitly, opening another notebook within or going back to one I defined as **Home**
- Wouldn't it be great to have _back_ and _forth_ buttons like DevonThink or a browser?
Maybe I'm missing out on something, but from an UX perspective it can only see it unfortunate

Have a great day and go on with this piece of art of yours.

**Comment by dvorka** [comment]
Fixed by 723f66f0c49c680e7fc30a6301ce17b972840524

**Comment by dvorka** [comment]
**> It will as well be available in the Windows version too, I hope?**

Yes, it will.

**> Am I mistaken or are notes just segments (Notion would call them blocks) of a notebook?**

**Notebook** is a document (Markdown file), **note** is a section of a document.

**> I struggle to get back to, say all notebooks if I open one of them**

<kbd>Alt-Left</kbd> or <kbd>Ctrl-Shift-O</kbd> or <kbd>Alt</kbd>,<kbd>v</kbd>,<kbd>o</kbd> or use menu.

**> Home**

Home (perhaps should be called home notebook) is a Notebook which you use often (not a list of Notebooks/Note).

**> Wouldn't it be great to have back and forth buttons like DevonThink or a browser?**

Back is <kbd>Alt-left</kbd> as I described above. For forward navigation you can use recent Notes/Notebooks view (much faster) w/ <kbd>Ctrl-Shift-r</kbd> (or menu).

@herop Jochen, thank you for your suggestions and interest in MindForger!
