### ISSUE TITLE
Markdown Preview

### ISSUE THREAD

**Issue by phi1010** [dvorka/mindforger#1267]
The documentation mentions a "Markdown Preview", but I can only find the view and edit modes. A preview of the note currently being edited as a side-by-side-view (like hackmd.io, for example) would be nice. For long notes, a scroll synchronization mechanism might be necessary.

**Comment by dvorka** [comment]
Side-by-side/live preview finally released in 1.51.0 https://github.com/dvorka/mindforger/releases/tag/1.51.0
