### ISSUE TITLE
Editor: smart indentation (indented line, lists)

### ISSUE THREAD

**Issue by phi1010** [dvorka/mindforger#1268]
Lists and code excerpts in markdown rely on indentation; which can profit from two features:

a) Keep Indent:
When starting a new line, the new line should begin with the same indent as the first line above that contains text. This avoid's the need to reindent each line manually.

b) Indent Refactoring:
To refactor lists, a user usually needs to (de-)indent the code in the list levels below; usually via <kbd>Tab</kbd>/<kbd>Shift+Tab</kbd> on marked text in most IDEs. Currently, this just replaces the marked text with a tab.

**Comment by stexyz** [comment]
c) `tab` works as expected - adds spaces (4 by default) and allows for indentation of list items etc (not as smooth as if the indentation level of the above line was kept but still ok). `shift-tab` doesn't work this way but instead jumps to the name of the note(book). It would be very useful if it deleted four spaces before (=did the opposite of `tab`).

**Comment by dvorka** [comment]
@phi1010 @stexyz makes sense - increasing priority.

**Comment by dvorka** [comment]
Progress:

* [x] lists and code fence indentation
* [ ] shift-tab on line
* [ ] shift-tab on selected block
