### ISSUE TITLE
Eisenhower Matrix for individual notes

### ISSUE THREAD

**Issue by ablx** [dvorka/mindforger#1281]
At this moment, one can only set importance/urgency for whole notebooks.
It would be useful for me if one was able to set them for notes as well.
E.g. I create a notebook for each book I read and one note for each chapter. If I have open points for this chapter (e.g. do the excercises) I'd like to see that note in the matrix.

**Comment by Iznik285** [comment]
It would also be useful for me.

**Comment by dvorka** [comment]
Make sense. It would be useful for me as well :wink: Could be notebooks and notes mixed in Eisenhower Matrix view? (there would probably be a watermark indicating the type of the resource).

It may take some time for me to design the enhancement as I would have to add urgency and importance to notes metadata. But it would be definitely valuable.

Thank you for the suggestion!

**Comment by dvorka** [comment]
Eisenhower Matrix for individual notes with ability to sort notes using tags is implemented in f546072fd1d5233a2d43b064fb759645964628ce and will be released with 1.53.0.
