### ISSUE TITLE
Latex curly bracket not showing

### ISSUE THREAD

**Issue by fuggy** [dvorka/mindforger#1282]
Hello, thanks for developing this amazing tool that is Mindforger.

I found another bug with LaTeX writting, witch I use a lot. The curly brackets won't show up when I write them like in : 
$\{x_1, \cdots, x_n \}$
or 
$\forall x,y∈M,  d_M(x,y)  =   \inf_{g∈G} \{ d_G(Id,g)|g·x=y \} $ 

Don't know why tho.
Thank you 
Anton

**Comment by dvorka** [comment]
@fuggy MindForger uses MathJax to render math expressions. It seems that the problem might be solved/workarounded by quoting them like `\\{` and `\\}`:

* https://stackoverflow.com/questions/41312777/mathjax-curly-brackets-dont-show-up-using-jekyll

I will let you know if I find a better solution. Thank you for your interest in MindForger!

**Comment by fuggy** [comment]
Yes it worked now ! 
It is also working the same way for bigger brackets by writting
>>>  \left\\{  \cdots \right\\}

Thank you !
