### ISSUE TITLE
Setting deadline in notes causes mindforger to close

### ISSUE THREAD

**Issue by Iznik285** [dvorka/mindforger#1288]
Edit a note
Click on properties
Tick Deadline:
Set a date in the future.
Click ok.
Click Cancel / Properties / Preview or Remember
mindforger closes and deadline is not saved in note properties

I am using Windows 10 / MF 1.52.0
If you need any further information let me know.

**Comment by dvorka** [comment]
Unfortunately not reproducible on MindForger 1.53.0 @ Ubuntu 18.04. Let me try your version on Windows.

**Comment by Iznik285** [comment]
Let me know if there is anything further you would like me to check. Happy to test.

**Comment by Iznik285** [comment]
Closed as being dealt with in #1363
