### ISSUE TITLE
Turning off main toolbar is not reflected in Adapt Settings

### ISSUE THREAD

**Issue by Iznik285** [dvorka/mindforger#1301]
A minor issue

Steps to recreate:
Right click the toolbar and unchecking the Main toolbar checkbox.
Click on Mind / Adapt and under Application / show toolbar is still ticked.
You then need to click it off and on again to reshow the Main toolbar.

Windows 10 / MF 1.52.0

**Comment by dvorka** [comment]
Fixed by 9382c8fa402c4257a5156527d586d26b88a55587 - will be released in 1.53.0

**Comment by Iznik285** [comment]
Hi Martin,

I've tested this and can confirm it is now working as expected.
Many thanks.
