### ISSUE TITLE
Crashes when pressing "View Dashboard" button

### ISSUE THREAD

**Issue by evilyach** [dvorka/mindforger#1309]
Hello!

I'm on Windows 10 2004 x64, and I recently started using this app.

I am seeing a crash when doing the following:
1. Launching the app, it starts on `Dashboard` screen;
2. Tap in upper right corner (quadrant) in `Knowledge Graph Navigator`;
3. Tap several times on the `MIND` node;
4. Press the `View Dashboard`;
5. Enter the `Knowledge Graph Navigator` screen again;
6. Tap several times on the `MIND` node again;
7. Press the `View Dashboard` again.

This crashes my MindForger instance.

If you need more info, feel free to ask.

**Comment by bdenisiuk** [comment]
I was just about to post it.
Windows 10 Version 1909 (OS Build 18363.836)
Ryzen 5-2600 CPU 16GB Ram

When i click View Einserhower Matrix and than go back to View Dasboard fast (in like 1-2 seconds) it hangs.
When i give it a time - like 3-4 seconds it usually works normally.

**Comment by dvorka** [comment]
@evilyach @bdenisiuk thank you both for bug report. I will make sure it's fixed in the next MindForger release.

**Comment by dvorka** [comment]
Dashboard was experimental feature whose menu item was not hidden - 🐞 no longer reproducible dc83e2fac9d4b110863b8b505be4ad59ff6aedc5 as it was hidden (and will be removed in the next major release).

**Comment by dvorka** [comment]
* [ ] There is actually remaining bug - Dashboard wasn't removed from the **main toolbar**.

**Comment by dvorka** [comment]
Fix finished by c56b690 and 4699f87
