### ISSUE TITLE
vi keybindings in mac os version 1.52.0

### ISSUE THREAD

**Issue by rhaynes74** [dvorka/mindforger#1322]
Hi folks, the vi keybindings don't appear to work in version 1.52.0 on my mac, I have selected them from the adapt/editor window.  But no dice.

**Comment by FlorianHeigl** [comment]
same here :-)

**Comment by dvorka** [comment]
@rhaynes74  it's ashaming - I planned to support Vim keybinding, however, I never implemented it and option somehow alived from early days up until today. I removed the option in 4ee151cc16a66bb231d6f0dc5c962bf69722948e

Duplicate of https://github.com/dvorka/mindforger/issues/1410 and #1368
