### ISSUE TITLE
Minor bug: Dashboard view not updating on the creation of new Notebook

### ISSUE THREAD

**Issue by casperl** [dvorka/mindforger#1334]
Environment: MindForger 1.52.0 on a highly customized Ubuntu 18:10 environment.

Problem description: While in Dashboard view, new Notebooks are not being displayed in lists after creation.  The lists are seemingly not updated.

Replication of problem:

* Enter outline view with Ctrl-Shift-D
* Create new Notebook with Alt-O-N
* Dashboard view does not display the new file in either
  * Notebooks view (bottom right)
  * Recent Notes view (bottom left)
* Reloading Dashboard with Ctrl-Shift-D displays new files.

Expected behaviour is for new file to appear in Dashboard lists whenever created.

Note: New files do appear when created while in Notebooks view ( Ctrl-Shift-O )

**Comment by dvorka** [comment]
I decided to deprecate and remove Dashboard (1.53.0+ release no longer have it) - closing.
