### ISSUE TITLE
#9 - Pressing a unusable key combination causes no other hotkeys to register until disrupted

### ISSUE THREAD

**Issue by BNortonnul** [dvorka/mindforger#1351]
Try to create a new notebook while editing a note. This will disrupt any other direct hotkeys, and you'll have to interact with the "false" selection in order to be able to use any hotkeys.

**Comment by dvorka** [comment]
Fixed prior dda845b96ceeccc0654489f23d08ef9a655dd8a3 - Notebook can no longer be created using shortcuts nor from menu (menu is disabled).
