### ISSUE TITLE
Is Mindforger still being actively developed?

### ISSUE THREAD

**Issue by anthrolisp** [dvorka/mindforger#1358]
Is Mindforger still being actively developed? I love the outliner functionality with markdown files. Is there a roadmap for the future? Thank you in advance!

**Comment by dvorka** [comment]
@anthrolisp yes, MindForger is actively developed - the main reason for that is that I obviously use it on daily basis for anything and everything. However, time which I can devote to MindForge varies (I have full time job and family), so I work on smaller features and don't release it (as it takes a lot of time). 

Anyway, my summer holidays are close and I hope that I will have enough time to do another release. Features which I work on:

* **hierarchical** notebooks (notebooks can be organized to tree in the same way as notes)
* customizable (**tag** driven) **Eisenhower matrix** view
* Markdown syntax highlighting enhancements
* ... and hopefully most exciting is new **Voronoi treemap** based knowledge navigator (research / prototype)

... and more - please stay tuned ;-)

**Comment by sakkamade** [comment]
@dvorka, 
This is really great to hear!  :heart: For almost a year it seemed almost abandoned...
Thank you very much! I cannot wait for next release!

**Comment by nabaco** [comment]
+1 for the hierarchical notebooks!
My usecase is managing many different files under subdirectories, and I would like to see that as a hierarchy in mindforger.

**Comment by dvorka** [comment]
@nabaco make sense! This is actually feature I would use as well - I gave it higher priority and scheduled it to next milestone https://github.com/dvorka/mindforger/issues/1200 Thanks!
