### ISSUE TITLE
Creating a note with preview on doesn't put the cursor in the editor (1.52.0)

### ISSUE THREAD

**Issue by BNortonnul** [dvorka/mindforger#1361]
Welcome back, Dvorka. I was wondering if you got hit by a truck or something.
1. Have preview on.
2. Create a note.
3. Try to type immediately after doing so.
4. You cannot. You must click onto the edit area to begin typing. 
This is a pretty annoying QoL papercut. There's some other seemingly easy-to-fix issues in my previous issues as well.

**Comment by dvorka** [comment]
Reproducible on 6e8d249125cf284d1241efb37e738112e0dffe5a:

* to repro use **menu** (with <kbd>Ctrl-e</kbd> or <kbd>Alt-n-n</kbd> editor gets focus as expected)

I was able to repro it once (after toggling preview), however, exact repro steps must be added (as it works for me now)... anyway there is definitely a :lady_beetle:.

**Comment by BNortonnul** [comment]
I haven't had those limitations to reproduction. Here's a video, on 1.52.0:
https://youtu.be/dwXs4irTuxA

**Comment by dvorka** [comment]
Reproducible on:

* Win 10 (VM)
* `mindforger-1.53.0-4699f879.exe`

**Comment by dvorka** [comment]
Fixed (and tested) 508a557 ✔️
