### ISSUE TITLE
#11 - Setting a Note deadline crashes the program

### ISSUE THREAD

**Issue by BNortonnul** [dvorka/mindforger#1363]
Ditto to title.

**Comment by dvorka** [comment]
@BNortonnul unfortunately not reproducible on 6e8d249125cf284d1241efb37e738112e0dffe5a. Can you please share MindForger version (`mindforger --version`) and operating system? Also more details could perhaps help - do you simply open an existing note, change the deadline, close dialog and save it? Do you open a single Markdown file, directory or repository of files? Also what was deadline date you used. Thank you for the report and help!

**Comment by BNortonnul** [comment]
Adding a deadline of any time causes this issue. Mindforger 1.52.0 Windows x64:

**Comment by HarolddeBruijn** [comment]
Confirming this issue
on Windows 10 x64 21H1
Mindforger 1.52.0

**Comment by Iznik285** [comment]
Retested on dev/1.53.0 3939ae2a - 1.53.394 running on Win 10 20H2 and the issue still exists

**Comment by dvorka** [comment]
@Iznik285 thanks! I was also able to repro this 🐞 on 37a2547c99b8a70e31f96402fd9afdd7b27e6014 (1.53.0 WIP)

**Comment by dvorka** [comment]
Resolved by 8d47e97 - fix will be released with MindForger 1.53.0
