### ISSUE TITLE
Still developing? [Solved]

### ISSUE THREAD

**Issue by bastiano** [dvorka/mindforger#1365]
Hi! I've just installed MF, but I see the last update was 17 months ago. This is a great project. I hope it isn't abandoned.

**Comment by sakkamade** [comment]
https://github.com/dvorka/mindforger/issues/1358

**Comment by sakkamade** [comment]
@bastiano,
 So, could you close this?

**Comment by dvorka** [comment]
@bastiano please also check branches which I use to prepare new features https://github.com/dvorka/mindforger/branches prior merging it to `master`.

**Comment by dvorka** [comment]
Closing. Feel free to reopen if you have any additional questions.
