### ISSUE TITLE
Vim key binding not working

### ISSUE THREAD

**Issue by Alesnim** [dvorka/mindforger#1368]
I would use vim keys in mindforger and it desn't work. May i am do with it? 

MindForger versions: 1.52.0
OS: Manjaro

**Comment by dvorka** [comment]
@Alesnim it's ashaming - I planned to support VIM keybinding, however, I never implemented it and option somehow alived from early days up until today. I removed the option in ...

Duplicate of https://github.com/dvorka/mindforger/issues/1410
