### ISSUE TITLE
New CSS files can't be added via options, and are reset whenever the options are changed

### ISSUE THREAD

**Issue by BNortonnul** [dvorka/mindforger#1378]
This is a significant quality-of-life hangup for users wanting something besides the normal CSS preview styling. 

It would help to have a "Open file..." selector added for more easily adding custom styles, alongside the current drop-down selection.

If nothing else, it is certainly a bug that the options dialog fails to preserve custom CSS directories.

Windows 10 x64; Mindforger 1.52.0

**Comment by dvorka** [comment]
Hints:

* [ ] `Preferences dialog/Viewer/HTML Viewer/Viewer theme CSS/custom` to be added (`custom` item)
   * [ ] edit line w/ `Find CSS` button to be added below and enabled on `custom` selection
   * [ ] configuration persistence to be updated

@BNortonnul I'm going to implement ^, however, I'm unable to repro CSS reset when I choose one of the existing options in UI. Do you mean that CSS is currently reset when you modify `.mindforger.md` configuration file? (MindForger overwrites it with default when it starts, right?)

**Comment by BNortonnul** [comment]
The configuration is only overwritten (destroying the text-editor set CSS file) if I change something in the settings and save it. Without that, the custom directory is preserved.

**Comment by dvorka** [comment]
![feature-css](https://user-images.githubusercontent.com/2090143/141856266-db6622ca-e0ab-4162-a52c-a9066b6b91f5.png)

@BNortonnul fix 6a9454b with ability to specify CSS file in `Preferences` (custom file is no longer reset) will be released in MindForger 1.53.0

**Comment by BNortonnul** [comment]
Thanks!
