### ISSUE TITLE
Toolbar is not displayed on startup

### ISSUE THREAD

**Issue by Iznik285** [dvorka/mindforger#1391]
### Environment

- Mindforger version: 1.53.394 (dev/1.53.0 3939ae2a)
- Platform: Windows 10 20H2

 ### Steps to reproduce

Since the latest version whenever I start up Mindforger the toolbar is always turned off
I have to turn it on to reshow

![image](https://user-images.githubusercontent.com/63961864/142456477-50f08695-7fa4-422c-8427-11e588c388fb.png)

 ### Describe what you expected to happen

I would expect it to display or not depending on how I set it in a previous session

**Comment by dvorka** [comment]
This is obviously :lady_beetle: - thanks!

**Comment by dvorka** [comment]
@Iznik285 unfortunately I'm not able to repro it on 4563f0a9f5e1e15b411dc588d6fc6a584cf13056 (Linux). Can you please try it again?

I disabled toolbar, and started MindForger (toolbar is not visible) > I opened Preferences, enabled toolbar, and quit MindForger. When I start MindForger, toolbar is visible.

**Comment by Iznik285** [comment]
Hi dvorka,

I've downloaded the latest version that I can find. Nightly build dev/1.52.0 8bfc0de1 1.52.401.
After testing I can confirm that the issue is resolved. 
Many thanks for your help.

Regards

Jason
