### ISSUE TITLE
[Feature/Enhancement] Separate notes with blank lines

### ISSUE THREAD

**Issue by akinokonomi** [dvorka/mindforger#1398]
**Enha<ins>n</ins>cement / feature description:**
I'd like Mindforger to add blank lines between notes to improve readability of its Markdown files.

**Screenshots (with sketch), drawings, mocks, wireframes or diagrams:** (if available)
For example, this simple notebook:

![image](https://user-images.githubusercontent.com/91767492/143723960-ed63b17c-ca01-4eba-a14b-c03acaa023d2.png)

Produces this Markdown file:
```markdown
# Notebook <!-- Metadata: type: Outline; created: 2021-11-27 23:56:36; reads: 8; read: 2021-11-28 00:04:07; revision: 8; modified: 2021-11-28 00:04:07; importance: 0/5; urgency: 0/5; -->
# Note 1 <!-- Metadata: type: Note; created: 2021-11-27 23:56:36; reads: 4; read: 2021-11-27 23:56:53; revision: 2; modified: 2021-11-27 23:56:53; -->
Note 1 goes here...
# Note 2 <!-- Metadata: type: Note; created: 2021-11-27 23:57:01; reads: 5; read: 2021-11-28 00:04:07; revision: 3; modified: 2021-11-28 00:04:07; -->
Note 2 goes here...
```

Don't you agree that if it looked like this, it would have been much easier to read:
```markdown
# Notebook <!-- Metadata: type: Outline; created: 2021-11-27 23:56:36; reads: 8; read: 2021-11-28 00:04:07; revision: 8; modified: 2021-11-28 00:04:07; importance: 0/5; urgency: 0/5; -->

# Note 1 <!-- Metadata: type: Note; created: 2021-11-27 23:56:36; reads: 4; read: 2021-11-27 23:56:53; revision: 2; modified: 2021-11-27 23:56:53; -->
Note 1 goes here...

# Note 2 <!-- Metadata: type: Note; created: 2021-11-27 23:57:01; reads: 5; read: 2021-11-28 00:04:07; revision: 3; modified: 2021-11-28 00:04:07; -->
Note 2 goes here...
```

**Comment by akinokonomi** [comment]
Maybe even like this
```markdown
# Notebook <!-- Metadata: type: Outline; created: 2021-11-27 23:56:36; reads: 8; read: 2021-11-28 00:04:07; revision: 8; modified: 2021-11-28 00:04:07; importance: 0/5; urgency: 0/5; -->

# Note 1 <!-- Metadata: type: Note; created: 2021-11-27 23:56:36; reads: 4; read: 2021-11-27 23:56:53; revision: 2; modified: 2021-11-27 23:56:53; -->

Note 1 goes here...

# Note 2 <!-- Metadata: type: Note; created: 2021-11-27 23:57:01; reads: 5; read: 2021-11-28 00:04:07; revision: 3; modified: 2021-11-28 00:04:07; -->

Note 2 goes here...
```

**Comment by dvorka** [comment]
@akinokonomi I think that this is subjective and in general MindForger should not automatically reforemat/modify Markdown files it edits, **however**, I could make this option - user would enable this formatting and then it would be used on saving the files. Does it make sense?

**Comment by akinokonomi** [comment]
> MindForger should not automatically reforemat/modify Markdown files it edits

Right.

Really, I'm not so sure about it myself.

---

You see, I guess the problem is not really there: I thought that Mindforger already _does_  reformatting automatically (removes those blank lines automatically), but it turned out that it was I who was removing those blank lines myself in Mindforger.

Here is the screenshot of the _Note 1_:
![image](https://user-images.githubusercontent.com/91767492/146612279-e4142873-31a3-4e9e-ba59-69b20cf2ddbd.png)

As you can see, the note has one blank line visible above, and two lines below. I was likely removing them, thinking they are redundant.

So the main issue is that they should not be visible in Mindforger GUI.

However still, if Mindforger hides those blank lines in GUI, it itself should insert them as well, right?

Though I don't really want Mindforger to reformat the whole markdown files, instead I'd like to see it adding a blank lines before and after headers of note or notebook only when the new note or notebook is created. 
And _always_ hide those blank lines, if they are already present.

That how I see it, but as you say, it may be indeed subjective (although I thought that's how it supposed to be, see [daringfireball syntax](https://daringfireball.net/projects/markdown/syntax#header), or [daringfireball syntax.text](https://daringfireball.net/projects/markdown/syntax.text)), and I don't mind any solution as long as you see it as correct one.

**Comment by akinokonomi** [comment]
Hmm, now it looks overcomplicated to me.

And what if someone would like to use two blank lines, etc.?

No, sorry but now I don't know how this should be done at all, so I rather close the issue.
