### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by JamieSlome** [dvorka/mindforger#1399]
Hey there!

I belong to an open source security research community, and a member (@ning1022) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by dvorka** [comment]
@JamieSlome @ning1022 thank you for contacting me and advice. I created security policy https://github.com/dvorka/mindforger/blob/master/SECURITY.md and looking forward to your report!

Thank you again for heads up and your interest in MindForger!

**Comment by JamieSlome** [comment]
@dvorka - you should have received an e-mail from us with further details on the report.

Otherwise, you can view the private report directly here:

https://huntr.dev/bounties/571464df-a8cb-4980-abcb-63826e38d40e/

**Comment by JamieSlome** [comment]
@dvorka - it looks like our e-mail never made its way to you, apologies for this!

You should have just received an e-mail with further details on the report. LMK! 👍
