### ISSUE TITLE
lib/src/config/config.h should not include <sys/dir.h>

### ISSUE THREAD

**Issue by danfe** [dvorka/mindforger#1402]
This header is being phased out in modern Unix systems and used to mainly `#include <dirent.h>` and contain `#define direct dirent` for backwards compatibility.  On systems where it had been finally removed, like FreeBSD, this causes build failure.  The code in `config.h` already has needed (and correct) `#include <dirent.h>`.

**Comment by dvorka** [comment]
Fixed by 20a17f9e64695b2de9689f4cb6c28633fea6fe34 - will be released w/ MindForger 1.53.0

**Comment by dvorka** [comment]
@danfe thank you for the explanation! Fix is on the way.
