### ISSUE TITLE
Unbreak the build with CONFIG+=mfnomd2html

### ISSUE THREAD

**Issue by danfe** [dvorka/mindforger#1403]
Currently, there are several minor issues that prevent the build without MD2HTML.  Consider the following patches:
- [lib/lib.pro](https://cgit.freebsd.org/ports/tree/deskutils/mindforger/files/patch-lib_lib.pro)
- [lib/src/mind/ai/autolinking/naive_autolinking_preprocessor.cpp](https://cgit.freebsd.org/ports/tree/deskutils/mindforger/files/patch-lib_src_mind_ai_autolinking_naive__autolinking__preprocessor.cpp)
- [lib/src/mind/mind.cpp](https://cgit.freebsd.org/ports/tree/deskutils/mindforger/files/patch-lib_src_mind_mind.cpp)

**Comment by dvorka** [comment]
@danfe thank you Alexey!

**Comment by dvorka** [comment]
@danfe :lady_beetle: fixed by 15a00b6fbdafb84befbb81422480ff582a74af16 and will be released with MindForger 1.53.0

**Comment by danfe** [comment]
Nice!  I was not sure if iterating over `things` in that `for()` loop was actually correct or not.  If you could also unbreak the build with `CONFIG+=mfner` it would be even better! :-)

**Comment by dvorka** [comment]
`CONFIG+=mfner` is truly experimental build which I plan to remove in the next major release - let me at least mark it deprecated. It is **N**amed **E**ntity **R**ecognition machine learning NLP algorithm implementation atop MITIE. I made it work, however, it would be problematic for daily use. Therefore I will implement it outside MindForger.

Anyway, @danfe thank you for your interest in MindForger and porting effort! :wink:
