### ISSUE TITLE
[Bug] C-O keyword shortcut to open Notebook on macOs no longer works

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#1405]
**Bug description:**

* C?-O keyword shortcut to open Notebook on macOs no longer works

**Environment:**

* MindForger version: 1.52.0
* Operating system: macOS
* Git SHA (in case of nightly/custom build): ...

**Steps to reproduce :lady_beetle::**

1. Go to Notebooks listing and press keyboard shortcut :lady_beetle: 

CC @stexyz

**Comment by stexyz** [comment]
Cannot reproduce any longer, most likely due to key binding not connected to MF.

**Comment by dvorka** [comment]
Closing as not reproducible - feel free to reopen.
