### ISSUE TITLE
Vim keybindings not working

### ISSUE THREAD

**Issue by santiyounger** [dvorka/mindforger#1410]
Hey, I'd like to give mindforger a try, however Vim keybindings are really important to my writing.

I was excited to see there are vim keybindings for the editor, however after turning them on in the settings, they don't work

![image](https://user-images.githubusercontent.com/51902730/123814300-32efea80-d8bb-11eb-94b0-d51caee0694b.png)

Are there any extra steps I need to do to activate it?

Thanks

Specs:

Garuda Linux
Mindforger installed through AUR

**Comment by ladydascalie** [comment]
Similar experience on a fresh build off the AUR on Manjaro.
I can't seem to find any error messages to help me diagnose either.

**Comment by dvorka** [comment]
@santiyounger @ladydascalie it's ashaming - I planned to support Vim keybinding, however, I never implemented it and option somehow alived from early days up until today. I removed the option in 4ee151c - I will add it back once it will be ready.

**Comment by santiyounger** [comment]
> @santiyounger @ladydascalie it's ashaming - I planned to support Vim keybinding, however, I never implemented it and option somehow alived from early days up until today. I removed the option in [4ee151c](https://github.com/dvorka/mindforger/commit/4ee151cc16a66bb231d6f0dc5c962bf69722948e) - I will add it back once it will be ready.

thanks for the update, keep us posted if you manage to implement it! Honestly I pretty much try to only use apps with vim-mode :) this would be a great feature for sure!

Thanks!
