### ISSUE TITLE
Mindforger Gets Groovy?

### ISSUE THREAD

**Issue by who8mypnuts** [dvorka/mindforger#1414]
Would it be possible to have a new build added to the ppa for Groovy Gorilla?

**Comment by dvorka** [comment]
Apologies, I missed the window of Groovy Gorilla Ubuntu release and as it's end of life https://wiki.ubuntu.com/Releases I cannot build and push the version to Launchpad. However, all subsequent current Ubuntu versions are and will be supported.

Closing as :lady_beetle: cannot be resolved.
