### ISSUE TITLE
[Feature/Enhancement] Page up/down, home/end not working in listings.

### ISSUE THREAD

**Issue by stexyz** [dvorka/mindforger#1420]
**Enhancement / feature description:**

In views like notebooks or recent notes on MacOS I cannot figure out how to use page up/down (tried standard fn+arrow, ctrl+arrow, even option+arrow); same for home and end.

**Comment by dvorka** [comment]
Fix remarks: https://stackoverflow.com/questions/57272759/how-to-pageup-pagedown-table-with-qtablewidget + jump to the beginning / end of table when no scrollbars and/or at the end.
