### ISSUE TITLE
[Feature/Enhancement] Add a (Mac) Shortcut for the New Notebook Action

### ISSUE THREAD

**Issue by stexyz** [dvorka/mindforger#1422]
**Enhancement / feature description:**

Add a mac shortcut for creating a new notebook like for a note (or show the shortcut in menu if it's already present).

![image](https://user-images.githubusercontent.com/5528489/147605625-4d69c4cd-3fc0-4660-9b7c-df580ff465a0.png)

**Comment by dvorka** [comment]
Fixed by f55811972a6ba1d85f6e6ea598444d31f68dd08c - will be released with 1.54.0
