### ISSUE TITLE
[Feature/Enhancement] Ask for saving changes when clicking on a link

### ISSUE THREAD

**Issue by stexyz** [dvorka/mindforger#1424]
**Enhancement / feature description:**
When editing, disable following links from the HTML preview leading to other notebooks or show a warning offering saving changes.
This leads to loss of the unsaved changes.

**Comment by dvorka** [comment]
Hints for the fix:

* `MainWindowPresenter::handleNoteViewLinkClicked(const QUrl& url)`

**Comment by dvorka** [comment]
Fixed by 097eeffc8fb553f7fe51b6cdf70f8943ddc6fecc
