### ISSUE TITLE
[Feature/Enhancement] Search/Filter note(book)s in listings

### ISSUE THREAD

**Issue by stexyz** [dvorka/mindforger#1425]
**Enhancement / feature description:**
The search box on top would be very useful to filter the note(book)s in the `View Notebooks/Recent Notes`.  It does nothing until confirmed and then opens full-text search which can be opened directly.

![image](https://user-images.githubusercontent.com/5528489/147607132-c39eeedc-b8cc-4730-97f0-65de9edf4282.png)

**Comment by stexyz** [comment]
Also, put focus into the search box.

**Comment by dvorka** [comment]
Apologies but I will not implement this enhancement - notebook/notes search has more advanced dialogs for searching, CLI is just another input for simple FTS and/or commands. It's rather experimental which - I'm still not sure whether I want to keep it or not. Will leave it as it is for now...
