### ISSUE TITLE
[Bug] Hotkeys don't work (Mac)

### ISSUE THREAD

**Issue by stexyz** [dvorka/mindforger#1429]
**Bug description:**
Y/N key does nothing (tried with C, Command, Alt, Fn too)
![image](https://user-images.githubusercontent.com/5528489/147611166-8c6a4724-e754-457e-ae91-9d6f1762068b.png)

**Comment by dvorka** [comment]
Make sense (`main_window_presenter.cpp` > set shortcuts of custom buttons created by me.

**Comment by dvorka** [comment]
<img width="1440" alt="Screenshot 2022-01-08 at 19 16 06" src="https://user-images.githubusercontent.com/2090143/148655136-ad6b0a93-ae0a-4adb-bf39-32c3571dc290.png">

Fixed by <kbd>command-y</kbd> or <kbd>command-n</kbd> shortcuts c250faba8a4cb26d1900a87ae031336920ce4c39
