### ISSUE TITLE
[Bug] Diagrams Don't Work (Mac)

### ISSUE THREAD

**Issue by stexyz** [dvorka/mindforger#1430]
**Bug description:**
Sample diagrams provided along with MF.

![image](https://user-images.githubusercontent.com/5528489/147611526-29edecfe-580e-4bc7-9d8d-7ba2c794bc6a.png)

**Comment by dvorka** [comment]
@stexyz Diagrams are disabled by default (make preview slightly slower - depending on network speed). You can enable it from preferences.
