### ISSUE TITLE
Improve the UX for adding tags

### ISSUE THREAD

**Issue by stexyz** [dvorka/mindforger#1435]
Improve the UX for tagging when creating new note/notebook. Currently to add several tags I need to do some typing and mouse clicking. 

Thinking about the way tagging works in gmail for instance - press "l", type a bit and hit enter. [x]

![image](https://user-images.githubusercontent.com/5528489/148127440-1ed29ab7-cff8-4b0c-9db7-8c5b4bb4de24.png)

**Comment by dvorka** [comment]
I won't be able to change suggest box title, however, I can at least change `Add` button text:
* `Add existing tag`
* `Add new tag`

**Comment by dvorka** [comment]
@stexyz as customisation of completer would be complicated, I did what you can see in video - WDYT?

https://user-images.githubusercontent.com/2090143/148654327-9ae19f67-60bf-47eb-84a3-21b98f8d5ba7.mov
