### ISSUE TITLE
There is no rpm package in the latest github release

### ISSUE THREAD

**Issue by chapati** [dvorka/mindforger#1436]
There is no rpm package in the latest github release (v1.53.0). Would you please fix this. May be also consider AppImage/Flathub? Appimage on appimage hub has not been updated since 2018.

I was able to build from sources on Fedora 35 but I guess others might miss the rpm file. Also build was not without issues, hunspell lib was not found by ld. Fixed by changing LIBS += -lhunspell ->  LIBS +=-L/usr/lib64/libhunspell-1.7.so (quite dirty)

**Comment by dvorka** [comment]
@chapati I didn't have time to build it yet, but I will add `.rpm` as soon as I have time. I will also check `AppImage` build complexity. Thank you for your interest in MindForger!

**Comment by chapati** [comment]
I've recently had experience with packing qt5 and webengine based app into AppImage:

1. Used the following tool: https://github.com/probonopd/linuxdeployqt
2. Here is my build script with some issued fixed that I've stumbled upon

https://github.com/BeamMW/beam-ui/blob/master/.github/workflows/build.yml
Section `- name: AppImage [ubuntu-16.04 || ubuntu-18.04]`

3. Need to build on the OS with the lowest GLIBC supported or it would fail, for now it is Ubuntu 18.04

Hope that helps a bit. You're making a great project! Thank you.

**Comment by dvorka** [comment]
@chapati thank you! It's really nice GitHub Actions workflow - will definitely use it 👍

**Comment by dvorka** [comment]
.rpm for Fedora 35 is ready: https://github.com/dvorka/mindforger/releases/tag/1.53.0

Closing this issue, however, AppImage suggestions from @chapati are persisted in my development remarks as well as build/appimage directory readme.
