### ISSUE TITLE
How to change UI Font 

### ISSUE THREAD

**Issue by Iznik285** [dvorka/mindforger#1441]
Hi dvorka,

Many thanks for the new major release 1.53. Appreciate all the hard work that goes into this.

I have had time to upgrade but am having an issue with the UI Font.  

### Environment

- Mindforger version: 1.53.0-4699f879
- Platform: Windows 10 20H2

### Steps to reproduce

On version 1.52.0 the default UI font was:

![image](https://user-images.githubusercontent.com/63961864/148683466-2e761071-b7a2-4cb8-930a-e1836d9a8237.png)

On version 1.53.0 the default UI font is:

![image](https://user-images.githubusercontent.com/63961864/148683482-f1f95db4-2ec4-4c2b-8eca-42615adf610b.png)

### Describe what you expected to happen

How can I change the font to match the 1.52.0 version? I have tried updating the css file using the ones located here https://github.com/dvorka/mindforger/tree/master/app/resources/qt/css but this doesn't change the UI font. Any help would be appreciated

**Comment by dvorka** [comment]
@Iznik285 apologies - it's my fault - I changed font in light MindForger theme as I liked it more on Windows. Unfortunately it cannot be changed back using configuration now, **however**, I will add make it possible. Once it's fixed I will post to this issue (then you can either pick nightly installer build OR wait for the release - which should happen sooner than usually as it will be just fix release).

**Comment by Iznik285** [comment]
Hi dvorka, No problem. I was finding it looks a little too washed out. The 1.52 ui font was in bold which made it easier to read.
I look forward to hearing from you when you have a fix release.

**Comment by dvorka** [comment]
@Iznik285 I added more themes allowing you to choose between themes with and w/o fixed font in d91ef44cb4d7c3ad1f8faf9a56899d2c5f9b169d

**Comment by dvorka** [comment]
d91ef44 fix verified on Win 10 VM.

**Comment by Iznik285** [comment]
I can confirm that this is fixed on 1.53.522 (a3c32c5). Its looking a lot better on my screen. Nice to have the choice of themes too. I think this is a helpful addition. Many thanks for your help
