### ISSUE TITLE
Choose CSS dialog box after Startup[Bug] 

### ISSUE THREAD

**Issue by Iznik285** [dvorka/mindforger#1442]
**Bug description:**

I am using a custom css file. When I choose Adapt for the first time after reloading Mindforger, it opens the load custom css dialog box and I have to choose the css file each time.

**Expected behaviour:**

Dialog box should only open when I change the css file

**Environment:**

* MindForger version: .1.53.506
* Operating system: .Windows 10 20H2
* Git SHA (in case of nightly/custom build): 3d2cec6f

**Steps to reproduce :lady_beetle::**

1. Go to Mind / Adapt 
2. The Choose CSS dialog box immediately opens on entering after restarting Mindforger

**Comment by dvorka** [comment]
Thank you for the report - it's not reproducible on other platforms. Let me repro this 🐞 on Windows with released installer.

**Comment by Iznik285** [comment]
I have done some further testing on 1.53.511 3bee6b65 and can confirm that this only happens when a custom.css is selected.

![image](https://user-images.githubusercontent.com/63961864/148805727-d2cfc2fb-4ee5-4776-bff8-0818fda418c3.png)


 If the other 3 options are chosen it doesn't happen

**Comment by dvorka** [comment]
@Iznik285 thank you for additional debugging - it helped! I hope that I fixed 🐞 in d91ef44cb4d7c3ad1f8faf9a56899d2c5f9b169d

**Comment by dvorka** [comment]
Fix d91ef44 verified on Win 10 VM.

**Comment by dvorka** [comment]
@Iznik285 Would you mind to share your CSS so that I can make it one of MindForger build in CSS? It would be really great. Just asking ;)

**Comment by Iznik285** [comment]
I can confirm I tested it with 1.53.522 (a3c32c52) and all worked as expected. I was using your light.css to test, I haven't progressed much with my own css but as I do I will share. Many thanks for your help.
