### ISSUE TITLE
Changes to the note made by the external editor are not remembered

### ISSUE THREAD

**Issue by maaca** [dvorka/mindforger#1446]
**Bug description:**

MindForger 1.53.0, external editor is configured as `gvim -f`

When I edit the note by the external editor, the change is visible in the preview. After closing the MindForger and reopening it, the change disappears. Using the integrated editor, everything works as expected.

**Expected behaviour:**

The note is remembered.

**Environment:**

* MindForger version: 1.53.0
* Operating system: Linux Fedora 34

**Steps to reproduce :lady_beetle::**

1. Go to notebook
2. Press ctrl+x and do the change in the external editor 
3. check the preview
4. close the MindForger
5. open the MindForger
6. the change is not there

**Comment by dvorka** [comment]
@maaca thank you for the :lady_beetle: report - unfortunately it's reproducible. Will fix it for the next release.

As **workaround** edit the note in MindForger after you leave external editor and see your changes in preview: edit note (with <kbd>Ctrl-e</kbd> or from menu) and hit <kbd>Ctrl-s</kbd> to save or <kbd>Alt-LEFT</kbd> to save your changes and leave editor.

**Comment by dvorka** [comment]
🐞 fixed by 957e7f2

Feel free to use [nightly build](https://github.com/dvorka/mindforger#installation) (Windows installer, .dmg) or wait for the next release.

**Comment by maaca** [comment]
Thanks for the quick fix. I've built MindForger from the dev branch and everything works as expected.
