### ISSUE TITLE
Spell check config instructions on Windows are incorrect

### ISSUE THREAD

**Issue by Iznik285** [dvorka/mindforger#1448]
I have installed the spell check and will test. Another useful addition
The documentation is slightly incorrect. 

Currently it states:

Install vocabulary:

extract .sox archive downloaded from the URL above to get .dict and .aff files
copy downloaded (.dict and .aff) vocabulary files to one of the directories on Hunspell's search path

This should be changed to:

extract .oxt archive downloaded from the URL above to get .dic and .aff files
copy downloaded (.dic and .aff) vocabulary files to one of the directories on Hunspell's search path

**Comment by dvorka** [comment]
@Iznik285 good catch - thank you!

Fixed by https://github.com/dvorka/mindforger-repository/commit/b042d1276c1ad4221ec8171ce335ddc7d9cb38f4 - closing.
