### ISSUE TITLE
[Bug] Edit button in html view fails based on the "double click view to edit" setting

### ISSUE THREAD

**Issue by GuillaumeGenier** [dvorka/mindforger#1452]
**Bug description:**
The edit button in the html view does not work properly if the parameter "double click view to edit" is disabled in "file/preferences/viewer".
This happens in both "nerds" and "normal" menu display modes.

**Expected behaviour:**
The edit button in the html view should still work not matter the state of "double click view to edit" in "file/preferences/viewer"

**Environment:**
* MindForger version: 1.53
* Operating system: Windows 10
* Git SHA (in case of nightly/custom build): [1.53 release] 21ee305a22a29216123848b1a2d7e99e6d1bdc1e 

**Steps to reproduce :lady_beetle::**
1. Go to "file/preferences/viewer"
2. Ensure that "double click view to edit" setting is _disabled_
3. Opens any notebook to see an html view.
4. Click the edit button. The note will not swap into edit mode.

If the "double click view to edit" is enabled, the edit button works as intended.
**Screenshot:**
![image](https://user-images.githubusercontent.com/91501194/149805763-cdf54096-4d13-42f0-89c1-8d22034d973a.png)

**Error message or log:**
There is not error messages on the GUI of mindforger.

**Comment by dvorka** [comment]
@GuillaumeGenier thank you for 🐞 report!

**Comment by GuillaumeGenier** [comment]
The Ctrl-e shortcut does not work if the html view is in focus. 
However, if the focus is on the outline, it works like you said.
As I didn't compile the dev version of mindforger, I don't know if it is actually working on it.

**Comment by sakkamade** [comment]
> The edit button in the html view does not work properly if the parameter "double click view to edit" is disabled in "file/preferences/viewer".

That was already fixed, see https://github.com/dvorka/mindforger/issues/1310#issuecomment-1006095362

> The Ctrl-e shortcut does not work if the html view is in focus.

And Ctrl+e works for me in both cases. (I use build on this commit 3bee6b65.)

Arch Linux

**Comment by GuillaumeGenier** [comment]
As the bug should be fixed on the next version, I close this issue.
