### ISSUE TITLE
[Question] Stop Peview from Bouncing while in Edit

### ISSUE THREAD

**Issue by djsudduth** [dvorka/mindforger#1463]
On Windows 10 the live preview feature while editing a note causes the preview text to bounce up and down every time the preview window refreshes. If I'm typing a note the constant preview bouncing every refresh cycle makes it impossible to keep that window open since it is so distracting (even if the refresh time is extended). 

Is there an attribute or screen setting to stop that or is that a feature/bug?

Thanks!

**Comment by dvorka** [comment]
@djsudduth unfortunately this is know issue - you can get rid of "bouncing" by disabling MathJax support (which is causing slow/inconsistent rendering:

* go to menu `File`, `Preferences`
* click `Viewer` tab
* disable (uncheck) `math support`

Thank you for the question and your interest in MindForger. I will try to think about what can I do to avoid this issue in preview (as I don't like it as well). I will also add your question to FAQs.

**Comment by djsudduth** [comment]
Thank you! Turning off that setting worked for now. Looking forward to your next release.
