### ISSUE TITLE
Version not updated for 1.54.0 in lib/src/app_info.h

### ISSUE THREAD

**Issue by danfe** [dvorka/mindforger#1471]
It still says 1.53.0 which is confusing as it appears in the About dialog and window title.

**Comment by danfe** [comment]
Never mind, checked the tagged tree only, not the master.

**Comment by dvorka** [comment]
@danfe thank you for being on guard Alexey! I can see that you closed the issue, but still - there is no problem with binary distributions, right? No release bistro shows 1.53.0, right? If there is any problem, please report it back to me - I can do patch release to fix eventual problem(s). Thanks again!

**Comment by danfe** [comment]
I don't think that making another patch release just to fix 53 -> 54 is warranted.  Package maintainers should simply patch it before building if they use vanilla 1.54.0-tagged sources, not a bit deal.
