### ISSUE TITLE
[Question] Home Pages Font Size

### ISSUE THREAD

**Issue by djsudduth** [dvorka/mindforger#1473]
Unfortunately, as I get older - the fonts on the main page of mindforger are exceedingly small (such as the hierarchical navigation list) on my Mac and I'm struggling to read the text. I can change the font size in markdown editor to a comfortable size but not in the main app pages. 

Is there a way to change the main page font size?

Thanks!

**Comment by djsudduth** [comment]
Not sure if  'mindforgerApplication->setFont(QFontDatabase::systemFont(QFontDatabase::FixedFont))' in `look_n_feel.cpp` is scalable. I don't know how Qt sets fonts when they're system fonts.

**Comment by LonanAedhia** [comment]
I have the same problem in windows, everything is written so small, I can't work with it. Is there a way to scale it? Is it possible to add an option to up or down the global interface font size?

**Comment by dvorka** [comment]
@LonanAedhia @djsudduth thank you for the report - increasing priority to solve this problem in the upcoming release.

Qt uses the font (for menu, dialogs and other widgets) specified by the system by default. It even uses the size specified by OS system scaler (on Linux). I will try to override it and test it both on macOS and Win.

**Comment by huntsfromshadow** [comment]
+1 on this. I just found Mindforger and it is exactly what I need, but the font is way too small on my MacBook air.

**Comment by djsudduth** [comment]
@dvorka - any updates on this? Seems Mindforger hasn't been updated in quite a while. Have you abandoned it?

**Comment by dvorka** [comment]
@djsudduth definitely I didn't abandon it. I use MindForger on daily basis - it's the first application which starts when my computer starts. I keep all my work and personal remarks in MF (for years). 

Yes, I unfortunately don't work on MindForger as much as in the past - it does what I need and on the platforms I use (Ubuntu/macOS) it is stable, I have a family, a few other projects and also full time job - which is particularly crazy these days as I work in a domain which is at the beginning of the next hype cycle..., but it's life. 

Anyway, last weekend I created brand new Debian PPAs for 10, 11 and 12. Week before I pushed a small enhancement which integrates MF with various tools. 

... in other words Mind Forger lives, at least a bit 😉

**Comment by dvorka** [comment]
@djsudduth definitely I didn't abandon it. I use MindForger on daily basis - it's the first application which starts when my computer starts. I keep all my work and personal remarks in MF (for years). 

Yes, I unfortunately don't work on MindForger as much as in the past - it does what I need and on the platforms I use (Ubuntu/macOS) it is stable, I have a family, a few other projects and also full time job - which is particularly crazy these days as I work in a domain which is at the beginning of the next hype cycle..., but it's life. 

Anyway, last weekend I created brand new Debian PPAs for 10, 11 and 12. Week before I pushed a small enhancement which integrates MF with various tools. 

... in other words Mind Forger lives, at least a bit 😉

**Comment by dvorka** [comment]
@djsudduth oh, and regarding the issue - my eyesight is also getting worse so, with high probability, I will have to do something about it soon.

**Comment by johnblommers** [comment]
Every day multiple times I use Mindforger on PopOS. It is solid as brick, performs extremely well even though I have thousands of notebooks and notes.

It's also used less frequently on my M1 Mac Mini and mid-2012 Macbook Pro. Solid there too.

I sync content among  these three machines via a shared directory using Syncthing.

Life with Mindforgr is good. 

But I understand that user expectations that Mindforger should continue to get features and new releases The number of active issues is, I think, more indicative that users really like Mindforger as opposed to there being problems that need fixing.

Thank you @dvorka for releasing Mindforger.

**Comment by djsudduth** [comment]
@dvorka thank you!!!! Glad to hear you're still supporting it! I really do plan to get my dev environment up to contribute!  So many options now with semantic embeddings and LLMs that could make your tool amazing!

**Comment by dvorka** [comment]
@johnblommers you made my day! ... thank you also for the Syncthing tip!

**Comment by dvorka** [comment]
@djsudduth Yes, we live in great times! And you are right - it's a great opportunity... of course I'm thinking about it too - LLM, RAG, dense retrieval, ... but I don't want to make any promises yet :wink:

**Comment by djsudduth** [comment]
Oh wow!! Fantastic @dvorka!!!!!
