### ISSUE TITLE
I think you can supplement the developer documentation. 

### ISSUE THREAD

**Issue by COMPUTER102** [dvorka/mindforger#1481]
Especially the translation guide, what are the QM files and TS files in the translation folder, etc.

**Comment by COMPUTER102** [comment]
Also, how to use these files. Thank you.

**Comment by dvorka** [comment]
:+1: I'm in the process of moving MindForger documentation from Markdown to [Wiki](https://github.com/dvorka/mindforger/wiki) and will add it there. Thanks!

**Comment by COMPUTER102** [comment]
I saw brand new documentation today. It's done exceptionally well! 👍👍Thank you so much.
