### ISSUE TITLE
[Feature/Enhancement]  Add encoding to html export

### ISSUE THREAD

**Issue by mseliger** [dvorka/mindforger#1483]
**Enhancement / feature description:**
When exporting a notebook to html, then there is no section which declares the character encoding. The charset is missing.
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"> <-- This is missing in the exported html document!
```

**Comment by dvorka** [comment]
Good catch Maria! Scheduling the fix for the upcoming release.
