### ISSUE TITLE
[Bug] Nightly download deleted due to being stale

### ISSUE THREAD

**Issue by Technetium1** [dvorka/mindforger#1495]
**Bug description:**
Appveyor deleted the last artifact since it's been 30+ days

Steps to reproduce:
1. Go to https://ci.appveyor.com/project/dvorka/mindforger/build/artifacts
2. See no artifacts
3. Notice the popup that says artifacts older than a month are deleted
4. Be sad there are no builds since last year.

**Screenshots:**

![image](https://user-images.githubusercontent.com/9877150/221436460-822775d5-2408-4bd1-b746-93d3189089c4.png)

**Comment by dvorka** [comment]
@Technetium1 I just triggered new build w/ latest enhancemens https://ci.appveyor.com/project/dvorka/mindforger/build/artifacts - thank you!

**Comment by dvorka** [comment]
^ ~44 commits in 1.55.0 and 1.55.1 which were not released yet :wink: https://github.com/dvorka/mindforger/compare/master...dev/1.55.1
