### ISSUE TITLE
[Bug] Can't get Wingman to work on Windows

### ISSUE THREAD

**Issue by djsudduth** [dvorka/mindforger#1533]
Thank you @dvorka for the recent updates to mindforger 2.0!! Super exciting to see. 

However, I can't seem to get Wingman to work for me.  I'm using Windows 10 right now with my OpenAI key. I was able to confirm the key works with other tools. But, every time I run Wingman I get
`ERROR: Error: request to OpenAI Wingman provider failed due a network error - Error creating SSL context ()`

Any ideas?  I tried the new key and model with Logseq and it worked fine - no network error.

Also, any way to pick the LLM? I typically use gpt-4-turbo.

**Comment by djsudduth** [comment]
@dvorka - installed the update and confirmed the configuration. I now have a new error:

`ERROR: Error: request to OpenAI Wingman provider failed due a network error - TLS initialization failed`

**Comment by dvorka** [comment]
@djsudduth let me try to repro that on a Windows machine different from the one I use for MindForger development. Thank you for reporting the :lady_beetle: !

**Comment by djsudduth** [comment]
@dvorka - you probably knew this - but in case it helps: https://stackoverflow.com/questions/53805704/tls-initialization-failed-on-get-request

**Comment by dvorka** [comment]
@djsudduth thank you! :lady_beetle: is reproducible on non-development Windows machine. I didn't fix it there, but the most probable root cause is missing OpenSSL and/or version mismatch. I will need to find out how to include missing libraries in the installer.

**Comment by dvorka** [comment]
@djsudduth I think that I solved problem with OpenSSL on Windows - please try `MindForger 2.0.1` (either link below or from the **Releases**):

* https://github.com/dvorka/mindforger/releases/download/2.0.0/windows-installer-mindforger-2.0.1-20365ac5-qt5152.exe

As a small thank you for your help I added ability to set your favorite [OpenAI model](https://platform.openai.com/docs/models) using environment variable :wink: 

```
# Windows
set MINDFORGER_OPENAI_LLM_MODEL=gpt-4

# Linux/macOS
export MINDFORGER_OPENAI_LLM_MODEL=gpt-4
```

Please give it a try!

**Comment by djsudduth** [comment]
@dvorka Fantastic!!! It works very well!  I tried some variations on notes and no issues at all. Thank you for the effort to fix it and adding the LLM option!

Side question: were there any enhancements to the ML 'thinking' model for associations?

**Comment by djsudduth** [comment]
Yeah, faiss makes good sense to try. There are plenty of RAG solutions to choose from for vector store and retrieval. Looking forward to what you might come up with. Thanks!
