### ISSUE TITLE
Diagrams are not rendered even when Mermaid library presents and saved HTML works for me

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#365]
If I use HTML generated by HTML representation, open it in browser, it works. In MF it does NOT work (I get no error message). CME made it work... (but uses an older version w/ CSS). Perhaps try to make offline version of diagrams work first using CME files. Then fix online.

**Comment by kuznero** [comment]
Same with me

**Comment by kuznero** [comment]
I have tried various different combinations enable/disabling mathjax, syntax highlighting, online/offline mermain js library. Nothing make mermaid diagrams render in preview in MindForger. It would be a great thing to have. Any idea about how can it be fixed? Perhaps some guiding such that I could come up with decent PR to fix it?

**Comment by kuznero** [comment]
I am using v1.48.2 btw.

**Comment by dvorka** [comment]
> Any idea about how can it be fixed? Perhaps some guiding such that I could come up with decent PR to fix it?

I will try to make it work locally and open that HTML from built-in MindForger browser to find out what's wrong. It might be security problem (loading of certain resources from certain locations), broken paths, ... will see!

Thank you @kuznero for raising this!

**Comment by StoltHD** [comment]
Same problem, only see the mermaid code
Have tried any and every thinkable way of writing it...

Running Windows 10 1903, Enterprice N, with Mediapack...
AMD RX570 GPU, Latest drivers.

Same simple example code runs in notable as a test, even though i need to go out of the note and back in to view the diagram after edit.

**Comment by mboelen** [comment]
Hi @dvorka - First of all, thanks for your work on this project.

Noticed that diagrams are not displaying for me, which looks like this issue. I'm using MindForger 1.49.2 (testing on Ubuntu). Tried offline/online library and enabled math support.

**Comment by flexbed** [comment]
Same for me, no mermaid diagrams. 1.49.2, running Ubuntu 18.04.3.
Does anyone have a workaround for this?

**Comment by johnblommers** [comment]
None of the Mermaid diagrams (flowchart, sequence diagram or gantt) render on Ubuntu 19.10 regardless of which online/offline library we try.

**Comment by DAlperin** [comment]
+1 Ubuntu 19.10 no diagrams render regardless of offline/online modes. Running v1.5.

**Comment by fcayci** [comment]
On my Linux system with 1.50.0, it seems the problem happens because ` ```mermaid` block creates a `<pre><code class="language-mermaid">` tag. Changing this to `<div class="mermaid"` (and accompanying closing tags) fixes the problem at least for after html exports. Probably needs a custom parser for mermaid blocks.

**Comment by dvorka** [comment]
@fcayci you made my day! Thank you for finding root cause! I should be able to fix the bug with your suggestion! Thanks!

**Comment by fcayci** [comment]
Well, thank you for this awesome tool!

**Comment by dvorka** [comment]
I just fixed a bug preventing Mermaid being injected 81cb404 + if user writes HTML (instead of Markdown) it works https://twitter.com/mindforger/status/1223156770715193344

**Comment by dvorka** [comment]
To get closer to straightforward Mermaid use, I will remove automatic prefixing of ``` block names with `language-` which breaks Mermaid integration. User can put there `language-` after ``` block w/ needed, but there is no way how to get rid of it.

**Comment by dvorka** [comment]
66acf98 fixes this bug and will be released w/ the next MindForger versions (1.51.0)
