### ISSUE TITLE
[cmark-GFM] MD 2 HTML: migrate from Discount to CMark

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#417]
Migrate to cmark GFM to get good Markdown 2 HTML support.

* because handles missing lines for lists and code blocks
* because it support more export formats
* because supports emojis
* because it's used by GitHub
* because it has better AST which can be used e.g. by autolinking

Resources:
* https://github.com/github/cmark-gfm
* https://commonmark.org/
* https://github.com/github/markup
* https://github.com/commonmark/cmark
* https://spec.commonmark.org/dingus/

The first step was refactoring of Discount code to extract interface #920, this feature is actual interface implementation using cmark.

Acceptance criteria:
* [x] abstract MD 2 HTML interface
* [x] cmark-gfm implementation
* [x] unit tests Win
* [x] unit tests Linux
* [ ] unit tests macOS
* [x] Travis CI
* [x] AppVeyor
* [x] debuild for Launchpad
* [x] documentation (build)

**Comment by dvorka** [comment]
@vlastahajek FYI, I just removed obsolete `cmark` module and added my fork of `cmark-gfm` module.

**Comment by vlastahajek** [comment]
Implementation of cmark-gfm md 2 html transcoder is done and successfully working on Windows. 

On Linux, it builds ok with cmark-gfm shared libraries, but it fails to built with cmark-gfm static libraries - #957.

There is also a missing piece, which is configuring parsing options and html render extensions. Currently all the available extensions  are employed and the `CMARK_OPT_UNSAFE` option is used.

**Comment by dvorka** [comment]
cmark-gfm checked on Ubuntu 18.04, Windows 10 and macOS 10.12 ... and distros can be build there (including Launchpad debuild).
