### ISSUE TITLE
Scope by tag(s)

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#429]
Add checkbox to scope dialog allowing to scope remarks by tags. For example I want to work on Os w/ `mindforger` tag only.

**Comment by tgharib** [comment]
I see mindforger is still in early development so this is definitely a lower-priority feature but it would be nice to have regex support so that I can search for all notes that don't have a certain tag for example.

**Comment by dvorka** [comment]
@tgharib Can you please describe in more details examples of searches you miss? You can use regular expressions to search for notes/notebooks - just use full-text search and use radio button to choose between exact/case/regexps, but only title and description, but not metadata, like tags. If you want to search for Ns which HAVE certain tags and do NOT have other tags, I could extend search by tag dialog/functionality (it should be simple). Thank you for raising this!

**Comment by tgharib** [comment]
>If you want to search for Ns which HAVE certain tags and do NOT have other tags, I could extend search by tag dialog/functionality (it should be simple).

Yes, this is my request.

**Comment by tgharib** [comment]
@dvorka: Actually, on second thought, I don't really need this feature and I don't think there is enough demand for advanced tag scoping as I am requesting to warrant the effort. I don't want to burden you with feature creep because that just makes the software harder to maintain.
