### ISSUE TITLE
Spellcheck for N editor

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#489]
* http://hunspell.github.io/
   * C++
   * used by LibreOffice, OpenOffice.org, Mozilla Firefox 3 & Thunderbird, Google Chrome... and many others
   * example Qt app using Hunspell https://wiki.qt.io/Spell-Checking-with-Hunspell
   * Hunspell license https://doc.qt.io/Qt-5/qtwebengine-3rdparty-hunspell.html
* https://github.com/manisandro/qtspell
   * ready to use component based on `enchant` spell-checking library.

**Feature status**:

* I work on Hunspell-based spell checking in https://github.com/dvorka/mindforger/tree/feature-489/hunspell-spellcheck branch
* remaining tasks
   * [x] load available dictionaries regardless spell check is enabled or disabled
   * [x] Windows: initialize "dirs" lookup dirs for dictionaries location
   * [x] Windows: test ^ lookup of OpenOffice dictionaries and spell check functionality
   * [x] if no dicts are found, then show label with link to documentation with platform specific how to

**Comment by gekaremi** [comment]
**Proofreading software: Spell, Grammar, Style Checkers**
great collection of libraries and tools
[http://stereobooster.github.io/proofreading-software](url)


**Improve Documentation by Automating Spelling and Grammar Checks**
[https://blog.codeship.com/improve-documentation-by-automating-spelling-and-grammar-checks/](url)

**Comment by gekaremi** [comment]
**Proofreading software: Spell, Grammar, Style Checkers**
great collection of libraries and tools
[http://stereobooster.github.io/proofreading-software](url)


**Improve Documentation by Automating Spelling and Grammar Checks**
[https://blog.codeship.com/improve-documentation-by-automating-spelling-and-grammar-checks/](url)

**Comment by s0kil** [comment]
Any progress on this?
I would suggest using [JamSpell](https://github.com/bakwc/JamSpell), It's accurate and contributes to the performant nature of MindForger.

**Comment by s0kil** [comment]
Recently encountered another useful project: https://github.com/languagetool-org/languagetool

###### *Hope you are still considering this (:*

**Comment by dvorka** [comment]
Feature is finally ready in 6724540a205872431aba398f1f760ef4296257e3 and will be released with MindForger 1.53.0
