### ISSUE TITLE
Request: Do you plan a windows version of MindForger?

### ISSUE THREAD

**Issue by mseliger** [dvorka/mindforger#632]
Do you also plan a windows version of Mindforger? At home I'll work with Lubuntu, but at work I have to use the Windows operating system.

**Comment by dvorka** [comment]
Yes, I plan Windows version, however, it's a low priority feature. I released MindForger a few weeks ago and there is no other contributor yet - I had to decide between porting to new platforms and new features... I chose the latter. Perhaps somebody from growing MindForger user/developer community will help. 

Thank you for your interest in MindForger - please [stay tuned](https://github.com/dvorka/mindforger/milestone/10)!

**Comment by chabad360** [comment]
is there a roadmap at all for how long this will take?

**Comment by dvorka** [comment]
I [plan milestones](https://github.com/dvorka/mindforger/milestones?direction=asc&sort=due_date&state=open) just for a couple of upcoming weeks. [Windows build and distro](https://github.com/dvorka/mindforger/milestone/10) is not scheduled - it depends on the demand. If everything goes smoothly, I will reserve ~2 days at the beginning of August to make an experimental build.

**Comment by SeriousM** [comment]
Hi! I follow mindforger for quite a bit now and notice the urge of a windows version. It's just a pain to use wsl with x server to run this nice application! Is it somehow possible that you could create an experimental build? This would give you a starting point to see what problems are left till a stable version.
Thank you very much for this super product!

**Comment by dvorka** [comment]
@SeriousM thank you for your comment! Unfortunately I can devote MindForger only limited amount of time. Therefore such feedback helps me to balance priority of features I should work on next. Based on you r comment (and several other emails, messages, ...) I'm going to reorder milestones and make https://github.com/dvorka/mindforger/milestone/10 the next one.

I think that I already know I have to do + @chabad360 also contributed by making experiments. I just need some time to make it work. I will update this issue with progress.

**Comment by SeriousM** [comment]
That's a good message, I'm glad you're happy! Just tell me when I can help
you testing!

**Comment by sbstn87** [comment]
Hi,

any updates on the Windows version? I am waiting for it to move entirely from OneNote to MindForger as there are no better alternatives and I do not want settle for anything else :)

Best regards,
Sebastian

**Comment by dvorka** [comment]
@sbstn87 I have bad news and good news. Bad news is that I didn't make any progress as I had to return to full time work (and now work on MF only in my spare time). 

**Great** news is that starting from Monday contributor (really skilled developer) will start working on windows MF version - *4 weeks fulltime*! It's big thing for me. You should see progress in Git repo (and I will share more details to this issue once he starts). If everything goes fine I hope to have native Windows MF version w/ installer by the end of February (latest).

**Comment by sbstn87** [comment]
That is wonderful! I will be waiting for the upcoming news and release.

**Comment by dvorka** [comment]
You can track progress in milestone https://github.com/dvorka/mindforger/milestone/10 and branch https://github.com/dvorka/mindforger/tree/dev/1.49.0-win

More details can be find in [developer documentation](https://github.com/dvorka/mindforger-repository/blob/master/memory/mindforger/developer-documentation/windows-build.md).

It's WIP. Any feedback is welcome. Stay tuned!

**Comment by sbstn87** [comment]
I can see that some progress is being made with the Windows version of MF - 60% done as of today.

Can you provide us with an estimated date of release?

**Comment by dvorka** [comment]
@sbstn87 great news that @vlastahajek did great job and port is basically done! The are just minor bugs/tags that needs to be finished which are mostly related to documentation, robustness and stabilization across all platforms (Linux, macOS, Win). 

I'm back in full time job so I will need 1 or 2 week(end)s to finish remaining work and release. Please stay tuned - we are almost there :wink:

**Comment by dvorka** [comment]
@mseliger @chabad360 @SeriousM and @sbstn87 - Microsoft Windows version of MindForger is out: https://github.com/dvorka/mindforger/releases/tag/1.49.0

As you know this is **the first** release - please report all problems, suggestions and feedback. Enjoy! :wink:

**Comment by sbstn87** [comment]
Wonderful! 

I will try it and let you guys know if I stumble on any issues. One suggestion I have is that the Windows version could default to the 'native' theme, otherwise it looks a bit out of place (at lest for me).

**Comment by dvorka** [comment]
@sbstn87 you are definitely right - I'm not satisfied with non-native l&f as well. I will try to improve it in #993

**Comment by dvorka** [comment]
Closing - Windows version has been released.
