### ISSUE TITLE
Don't use ctl-H for view/home, please

### ISSUE THREAD

**Issue by pcause** [dvorka/mindforger#639]
First, thanks for this software.  Looks very promising.

You have "View Home" bound to ctl-h.  for a lot of us ctl-h is bound to backspace.  when i use in mindforger nothing happens.

**Comment by dvorka** [comment]
You are right! I will remove <kbd>Ctrl-h</kbd> and leave there just <kbd>Alt-v h</kbd> ~ menu-based shortcut.

**Comment by dvorka** [comment]
Fix will be released w/ the next version.
