### ISSUE TITLE
Font size in Markdown preview

### ISSUE THREAD

**Issue by olablt** [dvorka/mindforger#643]
Hey, this looks like a great project!

What is the right way to increase the font size in preview window?

![image](https://user-images.githubusercontent.com/674574/42219446-a2fe21d2-7ed4-11e8-87d1-fd24ce9f0182.png)

**Comment by dvorka** [comment]
You can either use predefined CSS (there is just light and dark) or use your custom - probably the best option for you (there is no UI for such change for now):

1. make sure MindForger is not running
1. download CSS you like https://github.com/dvorka/mindforger/tree/master/app/resources/qt/css (dark or light and choose `Raw`
2. edit CSS and change font size
3. open `$HOME/.mindforger.md` and **change** path to your CSS, e.g.
```
...
* Markdown CSS theme: /home/olablt/my.css
...
```
Please let me know whether it helped. Thank you for your interest in MindForger!
