### ISSUE TITLE
[Win] Initial experimental build w/o Discount and other problematic deps/features

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#648]
Perhaps this should not be time consuming...

**Comment by chabad360** [comment]
Did you get any progress in this at all?

**Comment by dvorka** [comment]
No, I didn't and it would really help!

**Comment by chabad360** [comment]
Oops, ha, I meant to put this on the issue regrading building discount for windows

**Comment by chabad360** [comment]
But, maybe I'll also look into this while I'm at it

**Comment by dvorka** [comment]
Building Discount on Windows would help a lot as well! David Parsons mentioned that it could work, but he was not sure about that. Perhaps you could create a new issue for the build. Obviously I'm ready to help! Also you can let David know once his code builds.

**Comment by chabad360** [comment]
That might not be necessary if your moving to cmark tho

**Comment by dvorka** [comment]
True - I'm still not sure what's better choice. Anyway if you go forward and build it on Windows your work will not be wasted - Discount users will appreciate it + MindForger will be definitely using it for some time.

**Comment by chabad360** [comment]
Why not use cmark?

**Comment by dvorka** [comment]
For me it's mainly extra time needed for migration  (MF is still one man show) + minor bugs (like wrong links when HTML comment on line).

But from long term perspective IMO cmark is the way to go.

**Comment by chabad360** [comment]
You can make a wrapper, so the integration will be much easier

**Comment by dvorka** [comment]
Sure - #698.

**Comment by chabad360** [comment]
moving over to Cygwin, because you use so much POSIX specific commands, I think you'll need a more posix environment to build successfully

**Comment by chabad360** [comment]
Alright, I'm getting a syntax error in `lib/src/model/outline.h` at the `DELETE` enum in `Outline::Patch`. The error is `expected ‘}’ before ‘(’ token` and a few others like it, I can't find the reason for it, do you have any idea why it's coming up?

**Comment by chabad360** [comment]
Thanks, looks like thats done it, (I need to work on my google fu).

**Comment by dvorka** [comment]
> _moving over to Cygwin, simply because you use so much POSIX specific commands, and therefore you'll need a more POSIX environment to build successfully_

@chabad360 I really appreciate all the effort you invested in pure Windows build of MF. Overuse of POSIX is obviously my fault - I'm on Linux, I never implemented (bigger) C++ application and didn't want to have a (slower) portable lib dependency on the backend (`libmindforger.*`).

I don't want to waste your time! What do we get if you build MF using Cygwin. AFAIK Cygwin is basically a VM and user's will get the same app as via WLS, but slower.

Can you send a pull request whatever you have? Perhaps the solution would be to migrate from POSIX commands to a portable library (Qt might be the right choice), separate POSIX commands to a library and use Win API, or skip/don't provide some portion of the code on Windows (e.g. AI related stuff where I use threads, mutexes, ...) 

Can you name a few examples/location so that I know the impact of POSIX problem?

**Comment by chabad360** [comment]
I found them mostly in the `*_utils.h` but I didn't dig much deeper. Also, from what I understand cygwin is an actual port not a subsystem, they pretty much ported every thing over to a windows based system.

**Comment by chabad360** [comment]
Also strangly enough, `configure.sh` in discount uses `CRLF`, so you need to convert it using, say `perl -pi -e 's/\r\n/\n/g' input.file`.

**Comment by chabad360** [comment]
> I don't want to waste your time! What do we get if you build MF using Cygwin? AFAIK Cygwin is basically a VM and users will get the same app as via WLS, but slower.

Aside for what I said before, at least they'll get it natively.

**Comment by chabad360** [comment]
Another reason why it's better to switch from POSIX specific libs is that you'll have to bundle Cygwin and the necessary libs together with it. Meaning that paths and other stuff like that will be tied to Cygwin, and therefore more confusing for the end-user to use (regarding directories and the like). Whereas if you use MinGW (and I think Msys can do this too) all your dependent on is the Unix based build tools, which can build applications natively.

**Comment by chabad360** [comment]
Also, I'm getting `undefined reference to `__fentry__'` like right at the final build step.

**Comment by dvorka** [comment]
> I found them mostly in the *_utils.h...

Actually where I expected portability problems, I created such util w/ intention to rewrite it for given platform.

What should be next steps? What about rewriting `gear/*_utils.h` for Win? As I mentioned earlier this week I will be traveling next two weeks w/o internet/computer. When I'm back I would like to finish current mileston (knowledge graph) and they invest in Win.

**Comment by chabad360** [comment]
Yes `gear/*_util.h` would be a great start. I don't think rewiting should be to hard, I think it will just need some extra lines in most places. Or you could override the macros or definitions when compiling on win.

**Comment by vlastahajek** [comment]
Building and running MindForger is now possible , without MD->HTML rendering - Discount omitted
