### ISSUE TITLE
Xfce, ubuntu 16.04 Ctrl-e combination ignored

### ISSUE THREAD

**Issue by kv-gits** [dvorka/mindforger#664]
Can't edit note with hotkey.

Also Ctrl-S not works

**Comment by dvorka** [comment]
<kbd>Ctrl+e</kbd> issue is reproducible, <kbd>Ctrl+s</kbd> (note `Saved!` in status bar, use <kbd>Alt+left</kdb> to save and close note editor).

**Comment by dvorka** [comment]
Fix will be released w/ 1.43.0 - thank you for your submission and interest in MindForger!
