### ISSUE TITLE
Improve and fix navigation using Recent Notes

### ISSUE THREAD

**Issue by pcause** [dvorka/mindforger#676]
when i have associations and i click one, getting back to where i was seems difficult.  some sort of path back to the last few items i was viewing would make navigating and researching much simpler.  cross linking is so useful but when i use it in mindforger in this case, the navigation is so awkward that i can easily  lose my train of thought and instead spend time trying to get back to where i was and it is easy to lose context and thought process.

**Comment by rsuhada** [comment]
I have the same problem. Having foreward/backward buttons would be very helpful. There is also a recent list (which I think is for recently created notes), but would be nice to have a history (of visited notes).

**Comment by dvorka** [comment]
See also #692.

**Comment by dvorka** [comment]
@pcause @rsuhada I improved recent notes (view):
* I added toolbar with easy access to recent notes/notebooks (released - #692)
* I changed recent notes to be shown based on **read** timestamp, not modification timestamp (#781 - will be released with next version)
* I added also notebooks to the recent view (#781 - will be released with next version)

@rsuhada However, I don't know how to introduce backward/forward buttons (which could be clicked from anywhere):
* presume you are viewing note N1 (therefore it has fresh read timestamp)
   * list of notes ordered by read timestamp is: N1, N2, N3, ... (from just now to sometimes in the past)
* you click **back** button, MF finds most recent note N2 (skipping N1 self) and opens it (which modifies its **read** timestamp
   * list of notes ordered by read timestamp is: N2, N1, N3
* but when you click **back** button again, MF will open N1... and it will be showing only N1 and N2 and will not get **deeper** in the history i.e. it would be able to show just previous note
   * list of notes ordered by read timestamp is: N1, N2, N3
   * list of notes ordered by read timestamp is: N2, N1, N3
   * list of notes ordered by read timestamp is: N1, N2, N3
   * ...

Therefore I propose to open recent notes/notebooks view on **back** button and skip **forward** button for now. What do you think?
