### ISSUE TITLE
Menu item names

### ISSUE THREAD

**Issue by pcause** [dvorka/mindforger#677]
I know you are trying to make a point with the menu item names, and it is your product and choice, but why go out of your way to confuse the first time user?  Does it really add anything to the product to call it "Adapt" as opposed to "Preferences"?  I think it help draw people in if it is easy to get started and do things and then learn as you go.

Again, your product and you'll do what you like.  This seems promising and it would be great to see wider adoption so my comment is in the vein  of trying to get users to adopt and ease is always a factor.

**Comment by QuinnNguyen** [comment]
In the defense of MF the item name making the app more charming. And like any type of software there are definitely a learning curve for user to adapt too. I'm pretty sure if you want an friendly IDE or keeping note in simpler way you can using cherrytree or zim/ atom. I personally think the app existed for people who love to manage their knowledge base and really a note-taking enthusiast/researcher (and hopefully in future for general note taker). My point is, while the navigation is super confuse at first and take me a night to be comfortable with the layout, i dont think the names should be change at all. Just my 2cents after using various of hideous reference/research management products.

**Comment by dvorka** [comment]
@QuinnNguyen thank you - your explanation is perfect.

My motivation is to build human mind inspired thinking notebook. Yes, I'm probably loosing potential users, but I don't want to build yet another Markdown editor (which is in MindForger case just a side effect of a bigger vision).

**Comment by dvorka** [comment]
@pcause I changed my mind and decided to change **default** labels to align them with commonly used  terminology - it will be released w/ the next MF version https://github.com/dvorka/mindforger/milestone/16 I want to lower barrier for new users (I keep **nerd** menu which can be enabled in the configuration ;-) )
