### ISSUE TITLE
SegFault on WSL

### ISSUE THREAD

**Issue by chabad360** [dvorka/mindforger#712]
Mindforger builds perfectly fine but upon launch returns `Segmentation fault (core dumped)`.

This behavior started by commit 4b5c43a

**Comment by dvorka** [comment]
I just need to merge current `dev/1.45.0` branch to `master`.

**Comment by chabad360** [comment]
cool.

**Comment by dvorka** [comment]
Fixed by https://github.com/dvorka/mindforger/commit/3d56e6395ccbeb295f379b1caf80dc9c01f96dba + verified by building on WSL.

**Comment by chabad360** [comment]
thanks.

**Comment by dvorka** [comment]
:wink:
