### ISSUE TITLE
Show Repository name in window Title Bar

### ISSUE THREAD

**Issue by tengammaps** [dvorka/mindforger#722]
Just realized this is likely a dup, or cousin, of #92 ...

I hesitate to ask for features, especially small ones like this, because I don't want to seem ungrateful or unappreciative for the tool itself, the work to create it & the generosity to share it. However, it seems like its very much an active project for you, and I will make suggestions because I am excited about making MindForger a tool I  can use and rely on as a standard part of my work flow! So:

I'd like to have a little bit more context of the Repositories I'm creating. I see 2 ways to possibly do this:
1. Show repository directory name in the app title bar. (Perhaps in place of "Technology Preview"?)
2. Have a configurable MINDFORGER_REPOSITORY_HOME directory; provide a view of each subdirectory (presumably repositories) to make switching Repos easier than the current options ("Learn", "Remind", etc.)
* Eventually you could add Repository metadata in a Remember Repository dialog?

**Comment by dvorka** [comment]
@tengammaps please don't hesitate to send issues - I will really appreciate your ideas, suggestions and also constructive critics! I'm taking a few days off, but in 2 weeks I'm back. I scheduled this enhancement suggestion to the next release.

**Comment by dvorka** [comment]
@tengammaps to "...make switching Repos easier..." please use menu File/Recent or Mind/Remind.

**Comment by dvorka** [comment]
Path in main window title will be releases w/ the next MF version.
