### ISSUE TITLE
Crazy Idea: MarkText + MindForger

### ISSUE THREAD

**Issue by sebelk** [dvorka/mindforger#749]
I know, perhaps is an insane idea :-) but it would be awesome if marktext and [Mark Text](https://github.com/marktext/marktext) join each other, because both are great and complementary projects

What do you think?

Thanks in advance!

**Comment by dvorka** [comment]
It's a nice idea, however, IMO it's not realistic. Project use different programming languages (runtimes) and have different goals. Also MarkText is already very successful, while MindForger is just taking off. Anyway thank you for your interest in MindForger!
