### ISSUE TITLE
Change the taskbar 'plus' icon function depending on context

### ISSUE THREAD

**Issue by trimental** [dvorka/mindforger#768]
It would be nice if the 'plus' icon (the first) on the taskbar would change its behavior depending on the current window view. 

For example if you weren't currently navigating inside of a notebook then the 'plus' icon would add a new notebook but if you were then the 'plus' icon would add a new note to that notebook.

**Comment by dvorka** [comment]
Make sense! :+1:

**Comment by dvorka** [comment]
Fixed by 696cc1ddfc498d999ca2a2af8cdfe2eec414669a

**Comment by trimental** [comment]
Just to let you know, you put 'resolves #786' when it should be #768 :)

**Comment by dvorka** [comment]
This improvement will be fixed with the next MF version - 1.47.0
