### ISSUE TITLE
AUR version out of date

### ISSUE THREAD

**Issue by Icantjuddle** [dvorka/mindforger#841]
I don't know if the maintainers here have any communication with the maintainer [here](https://aur.archlinux.org/packages/mindforger/). But Arch User Repository package is fairly out of date.

**Comment by dvorka** [comment]
@Icantjuddle I'm aware of this issue as it has been reported by Arch users. Unfortunately I don't maintain the package and looking for a solution... (I contacted AUR maintainer and the package is already flagged). If you have any suggestion, please let me know.

**Comment by Icantjuddle** [comment]
It is possible to orphan the package and find a new maintainer. I will look into that.

**Comment by dvorka** [comment]
Thank you - I really appreciate it!

**Comment by Icantjuddle** [comment]
Closing as pkg is updated.

**Comment by dvorka** [comment]
@Icantjuddle this is great! I really appreciate it! (I apologize for the delayed reaction).

**Comment by LeBaux** [comment]
I would leave this issue open until the package finds new maintainer. https://aur.archlinux.org/packages/mindforger/

**Comment by dvorka** [comment]
@LeBaux done

**Comment by dvorka** [comment]
AUR https://aur.archlinux.org/packages/mindforger/ updated on `2022-01-04 18:02` thanks to `FabioLolix` + I can see updates around repo webs https://repology.org/project/mindforger/versions - closing. Feel free to reopen on regression.
