### ISSUE TITLE
MD syntax hiliter should ignore math mode

### ISSUE THREAD

**Issue by tsieger** [dvorka/mindforger#864]
(Minor issue:) editor syntax parser treats '_' in math mode as the markdown special character for emphasizing, not as the math special character for indexing. Consider this:

$RR = \frac{p_2}{p_1}$

Here, the text "2}{p" is show in italic in the editor, while IMHO it should not.

**Comment by dvorka** [comment]
Good catch @tsieger! I hate it as well. Let me check it's regexp config.

**Comment by dvorka** [comment]
Fix will be released in 1.50.0

**Comment by fuggy** [comment]
Hello dvorka
Thank you for developing this amazing tool that is mindforger :+1: 
This issue is still an issue.  
in $f_1$ some text $f_2$
'some text' is still highlighted
