### ISSUE TITLE
[UX] CUA mode should probably be default (not Emacs)

### ISSUE THREAD

**Issue by Skrylar** [dvorka/mindforger#871]
In the spirit of #191 and #687, the default control scheme should *probably* be set to the CUA compliant one (C-a selects all, C-x cuts, and so forth) if nothing else because that is what an overwhelming majority of onboading users are going to expect.

- Most users aren't coming from Emacs,
- Therefore they are going to assume the program is just broken because it doesn't act like gedit out of the box, and,
- the Emacsen are probably smart enough to open the config panel and turn the option on.

Although a one-time startup option that asks would also work.

**Comment by dvorka** [comment]
@Skrylar You are right. As Emacs user I was selfish :wink: Thanks!
