### ISSUE TITLE
Create note with a keyboard shortcut

### ISSUE THREAD

**Issue by cldwalker** [dvorka/mindforger#895]
Creating notes is something I do often and it would be helpful to stay on the keyboard when creating notes. Osx doesn't have a keyboard shortcut for accessing menus so I'm forced to use the mouse for each Note > New interaction

**Comment by dvorka** [comment]
Can be done w/ <kbd>Cmd-n</kbd> 0737ee9d219c3e5d5d8e079601e2855d7f54a6ae
