### ISSUE TITLE
Remember partially not working on osx

### ISSUE THREAD

**Issue by cldwalker** [dvorka/mindforger#896]
When editing a note in osx, invoking Remember doesn't save the note if invoked via keybinding Cmd-S or clicking menu item Note > Remember. If I click the upper-right dialog Remember button, it does work. This happens on a notebook with just one note

### Environment
osx 10.11.4
mindforger 1.48.2

**Comment by dvorka** [comment]
Fixed in 0737ee9d219c3e5d5d8e079601e2855d7f54a6ae, will be released w/ 1.52.0
