### ISSUE TITLE
Copy image to repository not working

### ISSUE THREAD

**Issue by modusV** [dvorka/mindforger#902]
Hey! Thank you for all the effort, I began to use mindforger a few days ago but I already love it. 

I wanted to report that in the Mac OS distribution the copy image to repository tick box is not working.

**Comment by dvorka** [comment]
@modusV shame on me - I put this feature to UI, but it's not implemented on the backend. Thank you for reporting this bug :+1:

**Comment by hannesfrank** [comment]
The corresponding feature issue is #436.

**Comment by dvorka** [comment]
Implemented by 0a7f39663993205e8726e44633fcb07cb7631896 - will be released w/ MindForger 1.50

**Comment by morsanu** [comment]
Hi! I have 1.50.0rc1 installed on a Windows 10 machine. This is still not working.

Thank you for your work.

**Comment by dvorka** [comment]
@morsanu Please download the latest version (1.52) from https://github.com/dvorka/mindforger/releases/tag/1.52.0 - it's fixed there.

Thank you for your interest in MindForger!
