### ISSUE TITLE
Mac create, delete and save note

### ISSUE THREAD

**Issue by modusV** [dvorka/mindforger#903]
Both the create, delete and save note shortcuts for the Mac OSX are not working.

MindForger 1.48.2
macOS Mojave v10.14

**Comment by technovangelist** [comment]
uh oh, over a year old and the ability to save still isn't there. this is kinda important.

**Comment by technovangelist** [comment]
So my temp solution/work around is to use Keyboard Maestro on the mac (though using hammerspoon will probably also work). Have a macro that responds to cmd s that saves the current mouse pos to a variable, then clicks the the button based on relative position, then resets the mouse pos. seems to work well but would rather not need it.

**Comment by dvorka** [comment]
Fixed by 0737ee9d219c3e5d5d8e079601e2855d7f54a6ae - will be released w/ 1.52.0 (<kdb>Cmd-n</kbd>, ... check app menu for details).
