### ISSUE TITLE
High CPU consumption: HD, Ubuntu 18.04, non-MF repo (Ivan)

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#910]
Upgrade Beast to 18.04 to reproduce the issue (related to #906, #897, #426)

* codereview for #590 first
* check Qt and kernel problems: https://www.google.com/search?q=qt+ubuntu+18.04+high+cpu+consumption

Machine reproducibility:

* Alien w/ LG, 18.04, 4k zoom: reproducible
* Alien, 18.04, 2k, no zoom: reproducible
* Beast, 16.04, FHD, no zoom: NOT reproducible
* S7, 16.04, <FHD, no zoom: NOT reproducible

Resources:

* http://doc.qt.io/qt-5/highdpi.html

**Comment by dvorka** [comment]
2019/1 update: it seems to me that after recent OS updates the problem disappeared (not closing as I want to be 100% sure this is fixed).

**Comment by dvorka** [comment]
2k/zoom 200%: paint() event loops on Os, Ns tree, ... and probably also in all other tables. The plan for now is to isolate which call causes the loop.

**Comment by dvorka** [comment]
I found the root cause - it's not stretch resize policy, but the policy combined with:
```
this->setColumnWidth(3, 0);
```
To hide column must be used:
```
this->setColumnHidden(3, true);
```

**Comment by dvorka** [comment]
Reopening: it's fixed for me, however, it's reported to be still reproducible by other users @ivan - there is still hope as the code layout color seems to be in the wrong method:
* https://stackoverflow.com/questions/54497951/qt-qtableview-paint-event-delivered-indefinitely-which-consumes-100-of-1-cpu

Reproducible on system: FHD, Ubuntu 18.04, MindForger 1.48.4:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

$ uname -a
Linux ivan-HP-ZBook-15-G2 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ md5sum /usr/bin/mindforger 
88cea3d810dc6677af2b3223329c994f  /usr/bin/mindforger

$ /usr/bin/mindforger --version
MindForger 1.48.4
```

**Comment by dvorka** [comment]
Fix ideas:
* move existing code to `resize()` method
* call `resize()` whenever presenter invokes `show()` of that method (`show()` to invoke `resize()` eventually()`)

**Comment by dvorka** [comment]
Reproducible on Win10 w/ Qt 5.12.1

**Comment by dvorka** [comment]
All `paintEvent()` code refactored to `resizeEvent()` except `LineNumberPanel` class where it the use seems to be legitimate (event is in addition passed to parent instance to be accepted there).

**Comment by dvorka** [comment]
Closing: resize strategy rewritten, paint event no longer used, not reproducible on Windows (~no system where I can reproduce it). 999aa762cbc4ed5e68b221e8e3a9b3dee4c62ec1

**Comment by ivankudibal** [comment]
no longer reproducible on my Unity Ubuntu 18.04
thus vfd on 1.49.0, thank you

**Comment by dvorka** [comment]
@ivankudibal great ;)
