### ISSUE TITLE
"Save Note?" dialog not shown always when leaving N which may lead to data loss

### ISSUE THREAD

**Issue by ktomk** [dvorka/mindforger#937]
When working with notebooks and notes and having the outline on the left next to the view and editor on the right often, very often, when editing and then clicking a different note - without any further notice - the changes are lost due to selection of a new document.

There is no automatic save nor is there a warning that informs about unsave edits that are going to be lost.

Often this happens after typing a lot, so a lot is lost. I would prefer automatic save and unlimited undo.

**Comment by vjfrancois** [comment]
I'm having the same issue.
While editing a note, a click on another note on the left side (note list in the same notebook) does not trigger the dialog box that asks if you want to save the edited note. I do have the dialog box if I use one of the search boxes.
Do you need more (technical) information to try and reproduce this behavior ?

Maybe making sure the dialog box is opened is enough, and we don't need a timed autosave.

**Comment by ktomk** [comment]
As I see traction here right now I'm a bit sorry that I couldn't port the issue so far. It's not that I would deny it per-se but just was not able to give it some love and traction. Sorry.

**Comment by dvorka** [comment]
New behavior: N is always saved automatically except <kbd>Ctrl+g</kbd> which cancels edit w/o saving.

**Comment by ktomk** [comment]
Automatic save sounds very good to me, it would have saved me from loosing those previously noted changes.

**Comment by johnblommers** [comment]
This is a **hugely** urgent and important issue to me. You can spend time in edit mode on a section and then click elsewhere in the outline and *poof* all your edits are gone. Either Mindforger should prompt you to <kbd>Save</kbd> or just automatically save the edits.

**Comment by dvorka** [comment]
@johnblommers which OS/distro do you use? (Ubuntu/Debian/Fedora/.../macOS/Win)? (actual fix would take less time than packaging and I could do minor release for you).

**Comment by ktomk** [comment]
me is on ubuntu.

**Comment by dvorka** [comment]
:+1: same as me. Tx!

**Comment by johnblommers** [comment]
My major platform is Ubuntu. It looks like several of us are looking forward to this fix :smile:

**Comment by dvorka** [comment]
Plan:
* [x] `Limbo` mgmt class w/ deprecation/purge policies 
   9d16306d1e611b4aad5f4a46e3c7b282f0f42cb5
* [ ] N editor close handler.
* [ ] application exit handler.

**Comment by dvorka** [comment]
![wip-save](https://user-images.githubusercontent.com/2090143/71548421-0dc0aa00-29ae-11ea-8b0c-0193d2ba0677.png)

... not pretty, but it avoids data loss...

**Comment by ktomk** [comment]
even not pretty, if there is an option to "autosave" this could get another button "always save and don't ask again" which then would be i assume the option of us heavy clickers ^^.

until then, this is much better - even not pretty - than loosing the edits.

**Comment by dvorka** [comment]
Makes sense :+1: Tx!

**Comment by dvorka** [comment]
@ktomk added both configuration:
![acfg](https://user-images.githubusercontent.com/2090143/71555845-8405f080-2a30-11ea-8e5d-7e525a995b89.png)
... and button to enable autosaving:
![adialog](https://user-images.githubusercontent.com/2090143/71555857-a435af80-2a30-11ea-93f5-b59f96d6fc45.png)
It can be disabled in configuration.

**Comment by ktomk** [comment]
Can't wait for the next release, thanks for taking so much care here! If you got development builds ping me where I can get them for testing.

And if you're open for some wording suggestion (from the screenshots): "Continue editation" (as in the screenshot) is perhaps easier understandable as "Continue editing" - but bear in mind that I'm a non-native English speaker so my contribution here is most likely limited.

**Comment by dvorka** [comment]
:+1: thank you for your suggestion and interest Tom! Right time - I'm just working on Ubuntu release (via Launchpad PPA) - did last minute change. I hope to have Ubuntu ready by tomorrow. Other platforms will follow...

**Comment by ktomk** [comment]
@dvorka: Thanks, thanks, thanks. As you feel prepared with the release, I hopefully feel equally prepared for testing. PPA is very fine for me. I also have no problems to install .deb packages directly if you prefer that for a test / if it helps.

**Comment by dvorka** [comment]
https://github.com/dvorka/mindforger/releases/tag/1.50.0 + https://launchpad.net/~ultradvorka/+archive/ubuntu/productivity/+packages see what you think :wink:

**Comment by ktomk** [comment]
WLAC, best unique Changes Save? - Yes / No / Cancel  modal dialog ever seen in a desktop app. - IMHO  autosave could be the default option / option by default but other uses should also report back, e.g. complaining about the dialog at all. Let it settle. THX A LOT.
