### ISSUE TITLE
Zlib (temporary) patch

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#951]
Is Zlib patch (after the installation) still needed? Can it be solved in a different way?

In addition I'm **not** able to apply given patch to `zconf.h` - can you please provide exact instructions like `patch zconf.h < zconf.path` (this doesn't work for me).

**PROPOSAL**: What about to make zlib MindForger's dependency to make it easier for anybody - simply create a repository and make it submodule in `mindforger/deps/zlib`?

**Comment by vlastahajek** [comment]
As discussed  in #952, the best solution would be to copy zlib files to another repo and apply this patch and make the change permanent.

**Comment by dvorka** [comment]
Fixed by making Zlib one of `deps/`.
