### ISSUE TITLE
[Win] C:\ installation > C:\users\[user] installation

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#952]
I think that installing MindForger to `C:\` root is bad practice and it could discourage devs from building it. I would like to allow user to build MindForger in any directory (ideally in their home) and specify paths relatively (suggesting all dependencies to be installed next to each other) - somehting like

```
%MF_BUILD_DIR%\
    mindforger\    ... mindforger Git repository clone
    zlib\     ... zlib
    ...
```
Where `%MF_BUILD_DIR%` is e.g. `C:\users\dvorka\projects\mindforger`.

I also think that `zlib` should perhaps go to `mindforger\deps\zlib`. WDYT?

**Comment by vlastahajek** [comment]
Sure, zlib is weak spot for the environment preparation. Is a pitty, there is not stanrd place for dev libs as is its on linux. Having it in separate repository and than in MF deps would be good solution. I will update all configs/project that will count with zlib in deps/zlib-win. Ok?

**Comment by vlastahajek** [comment]
All paths are relative. Zlib is part of dependencies. Documentation has been updated
