### ISSUE TITLE
Prepare cmd line scripts to built cmark, app, test

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#954]
Prepare script to make cmark.

**Comment by vlastahajek** [comment]
What would be the best set of windows scripts?
- build-cmark  (only)
- build-mindforger (only)
- build-tests
- build-installer
- release (build all)
- run-mindforger
- run-tests

**Comment by vlastahajek** [comment]
Added scripts:

- build-app.bat
- build-cmake.bat
- build-installer.bat
- build-unit-tests.bat
- env.bat 
- run-app.bat
- run-unit-tests.bat (parametrizable)

**Comment by vlastahajek** [comment]
Scripts are now mentioned in the documentation.
